### ISSUE TITLE
howto add ExtraKubeletFlags to machine deployment

### ISSUE THREAD

**Issue by HaveFun83** [kubermatic/machine-controller#1005]
Hi 
i'm search for a way to add ExtraKubeletFlags to a machine deployment.

Can someone tell me where to add the additional kubelet flags?

**Comment by kron4eg** [comment]
it's not possible to add free-form kubeletflags. Which flags exactly are you interested in?

**Comment by HaveFun83** [comment]
> it's not possible to add free-form kubeletflags. Which flags exactly are you interested in?

i search for an option to add the `--volume-plugin-dir` flag. I found this option hardcoded to `volumePluginDir: /var/lib/kubelet/volumeplugins` within the `pkg/userdata` now.

I know you already told me that you are working on the improvement of this topic. 
But maybe it can be possible to add more customization via annotations of a machine-deployment object?
