### ISSUE TITLE
Add support for Exoscale

### ISSUE THREAD

**Issue by tobru** [kubermatic/machine-controller#1013]
In addition to the already existing cloud providers I suggest adding https://www.exoscale.ch/ as an additional supported cloud provider. The Go SDK is on GitHub under https://github.com/exoscale/egoscale.

**Comment by kron4eg** [comment]
We are happy to accept contributions. Provider interfaces in relatively simple:
https://github.com/kubermatic/machine-controller/blob/6c98ea67c3c0b28f5ec0b6325105a9dbc94c5ee3/pkg/cloudprovider/types/types.go#L32-L77
