### ISSUE TITLE
BUG: Machines stuck at deletion

### ISSUE THREAD

**Issue by furkhat** [kubermatic/machine-controller#1015]
I created Azure machinedeployment. Waited for it to get healthy. Then I delete the machinedeployment. I waited for deletion of Azure resources corresponding to the machinedeployment. I verified deletion in Azure portal.

Actual state:
Machines are stuck at deletion and have`kubermatic.io/cleanup-azure-disks` and `kubermatic.io/cleanup-azure-nic` finalizers.

Desired state:
Everything must be deleted.

The problem occurred for azure, but could be general for all providers.

**Comment by furkhat** [comment]
To be clear - this does not happen all the time. I suspect it is related to a data race on controller-runtime pkg client side.

**Comment by furkhat** [comment]
Happened again, machines crds have the following finalizers:
```
    finalizers:
    - kubermatic.io/cleanup-azure-disks
    - kubermatic.io/cleanup-azure-nic
    - kubermatic.io/cleanup-azure-public-ip
 ```
while all the resources from azure were deleted.

**Comment by moadqassem** [comment]
@furkhat Have you actually checked that the above resources, disk and nic are deleted in the console?

**Comment by furkhat** [comment]
>  I can see that the evection has been triggered for more than 2 hours ago and it failed. The reason for that can vary. Before we delete machines we drain the underlying nodes. If draining the nodes fails for some reason(e.g: kubelet related issues or container runtime problem) then we stop trying evicting the machine.

@moadqassem what happens if someone deleted resources manually before machine-controller attempted to delete them?
