### ISSUE TITLE
Flatcar Linux User Data is to large for AWS

### ISSUE THREAD

**Issue by twittyc** [kubermatic/machine-controller#1055]
When provisioning machines with flatcar, the user data exceeds the AWS limit of 16384 bytes.

```
Warning  ReconcilingError  5s  machine_controller  failed to create machine at cloudprovider, due to failed create instance at aws, due to InvalidParameterValue: User data is limited to 16384 bytes
```

Machine controller version: 1.35.2
Kubernetes Version: 1.22.0
KubeOne Version: 1.13-rc0

**Comment by kron4eg** [comment]
@twittyc as a workaround, try to ether replace SSH key with shorter one (instead RSA type of key try to use ed25519) or even remove it entirely.

**Comment by twittyc** [comment]
So removing the Key allowed it to progress, but I really need to be able to add an RSA key. Does the machine-controller support launch templates? If so I can specify via a launch template.

**Comment by kron4eg** [comment]
Unfortunately not, it’s not supported and hardly will ever be. But you can always use a custom AMI.
