### ISSUE TITLE
Flatcar Provider AWS User Data Too Large

### ISSUE THREAD

**Issue by twittyc** [kubermatic/machine-controller#1095]
Hello,

I've updated machine-controller to version 1.36.1 from 1.35.0. The flatcar provider for this version breaks machine deployments in AWS. It seems the user data has grown beyond the maximum allowed size. I've even attempted removing the SSH key from the config. I know you guys are working on a PR to update the flatcar provider, but I thought you might find this useful as it's broken in the current release.

**Comment by embik** [comment]
@twittyc machine-controller 1.37.2 sets the provisioning utility for flatcar on AWS to cloud-init. Can you confirm that this release fixed your problem?

**Comment by twittyc** [comment]
This release did fix this issue thank you.
