### ISSUE TITLE
running machine-controller through leader election is optional

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#111]
the machine controller has been incorporated into kubermatic and is an inherent part of every cluster. 
That made local development/testing impossible as is highly possible that the machine controller which runs inside kubermatic will acquire a lock right before the local instance.

Making leader election optional seems to remedy this issue.

**Comment by alvaroaleman** [comment]
Would it be possible to instead define some kind of "group" or something alike that still does leader-election? IIRC the leader election creates uses an endpoint named `machine-controller`, maybe we could add a configurable suffix to that?

**Comment by p0lyn0mial** [comment]
good idea, I think we could just change the name of an `endpoint` resource. I think we could use `name` command line flag for that.

**Comment by mrIncompetent** [comment]
Yes, we should use the `name` flag for this. Its the same approach we do in the kubermatic-cluster-controller.

**Comment by kdomanski** [comment]
@mrIncompetent apparently you implemented large parts of this already in `805485026b7c2618c0fab91c75c8b0303a1c1245`. However, currently the grouping in cluster-controller uses a label, while the code in machine-controller uses an annotation. We should therefore change one of those.

**Comment by kdomanski** [comment]
Actually, there's an issue for it, #233. So do we agree to use labels in both services and drop the annotation?
