### ISSUE TITLE
Add servergroup for Openstack Nodes

### ISSUE THREAD

**Issue by qeqar** [kubermatic/machine-controller#1167]
Openstack put the (anti-)affinity feature in the server group and not in the VM resource.

In our setup the Scheduler returns a valid Hypervisor to any new machine and we end up to often with more then one Worker on one Hypervisor, which is bad for reliability.

The idea would be to create a Servergroup for every machine deployment and add a anti-affinity(affinity is the default) option to the cloudprovider spec.

That way we should have a better balancing of the machines and can keep the default, for older installations

**Comment by kron4eg** [comment]
hint:
The https://pkg.go.dev/github.com/gophercloud/gophercloud@v0.24.0/openstack/compute/v2/servers#CreateOpts doesn't have any "serverGroup" field, but extension https://pkg.go.dev/github.com/gophercloud/gophercloud@v0.24.0/openstack/compute/v2/extensions/schedulerhints#CreateOptsExt do, so `schedulerhints.CreateOptsExt{}` need to be used to create a VM.

**Comment by qeqar** [comment]
one update, if we create a group the default is affinity and that will result in creating all worker in the same Hypervisor!

If don't want to introduce new behavior, the default need so stay at 'no group' and then we have 4 more options:

- no group (as is)
- affinity
- soft-affinity
- anti-affinity
- soft-anti-affinity
