### ISSUE TITLE
adding userdata to worker nodes

### ISSUE THREAD

**Issue by qeqar** [kubermatic/machine-controller#1178]
At the moment, the machine-controller uses a hard coded ignition/cloud-config to create new worker.

We would like to insert extra options there, as the workaround with using a daemonset and a privileged Pod is not that good.

f.e at the moment we would need to set kernel parameter wit sysctl to get rid of some inotify problems.

**Comment by kron4eg** [comment]
Complete control over user-data customization is possible when using OSM.
