### ISSUE TITLE
Support osDiskType / dataDiskType for Azure

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/machine-controller#1191]
Currently, Azure machines are always created with "Premium SSD" os disk. Premium OS disk costs twice the "Standard SSD"

Our customer is looking at this as a cost-optimization measure and is looking to have an option to specify Standed SSD as option for diskType for Azure.

We already support similar feature for AWS and GCP. Kindly support for Azure as well.

**Comment by embik** [comment]
Just as a note, the disk SKU does not always default to Premium SSD. As far as I understand, the default disk SKU depends on the vm type (and maybe disk size?) selected, so in my tests my (small) nodes where deployed with HDDs.
