### ISSUE TITLE
GCE cloud-provider uses same ServiceAccount for GCE API access & machine

### ISSUE THREAD

**Issue by dajudge** [kubermatic/machine-controller#1194]
machine-controller's GCE cloud provider seem to use the same config
a) for creating the GCE client used to create machines
b) as ServiceAccount for the created machines

Here's the pieces of code I was able to identify:

a) https://github.com/kubermatic/machine-controller/blob/67e65cfb06df9da86f9e2fe9dfa9cad142c41060/pkg/cloudprovider/provider/gce/service.go#L55
b) https://github.com/kubermatic/machine-controller/blob/67e65cfb06df9da86f9e2fe9dfa9cad142c41060/pkg/cloudprovider/provider/gce/provider.go#L239
They both reference `cfg.jwtConfig` which is extracted from the service account blob here: https://github.com/kubermatic/machine-controller/blob/67e65cfb06df9da86f9e2fe9dfa9cad142c41060/pkg/cloudprovider/provider/gce/config.go#L200

I would love to create machines that don't have the elevated permissions required by machine-controller but so far I've been unable to identify a way to achieve this with the GCE cloud provider.

Am I missing some piece of the puzzle here?

**Comment by ahmedwaleedmalik** [comment]
With https://github.com/kubermatic/machine-controller/pull/1328 we added a way to disable the service account completely. That doesn't really facilitate this user request; a way to specify a dedicated service account for machines. I think this is still a valid use case and I'm thus re-opening the ticket.

**Comment by shatoboar** [comment]
We can either disable the Service Account, or we can just override the existing service account field here. 
 https://github.com/kubermatic/machine-controller/blob/73327a59cfdd95ccd0a5ac2852b45a5a16ae7c0f/examples/gce-machinedeployment.yaml#L41 
I don't think we will need a dedicated field for this.
