### ISSUE TITLE
Add ability to pass multiple node registry secret references via flag

### ISSUE THREAD

**Issue by dermorz** [kubermatic/machine-controller#1278]
In the context of https://github.com/kubermatic/kubermatic/pull/9260 it would be nice to have the ability to pass multiple registry credentials to be set on node level.

A possible implementation would be to extend the flag mentioned in [docs/registry-authentication.md](https://github.com/kubermatic/machine-controller/blob/master/docs/registry-authentication.md) to take multiple secret references as a comma separated list: `-node-registry-credentials-secret namespace/secret-name,namespace2/other-secret-name`

**Comment by kron4eg** [comment]
https://github.com/kubermatic/machine-controller/blob/ed424d935c061993ff70bbb0c3298653e7e68b1a/pkg/containerruntime/config.go#L96-L103

isn't this enough?
