### ISSUE TITLE
deadlock when trying to delete a machine

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#131]
Steps to reproduce :
1. Create an invalid machine - you can use the following manifest that doesn't specify required credentials https://github.com/kubermatic/machine-controller/blob/master/examples/machine-digitalocean.yaml
2. Delete the previously created machine.
3. List machine resources

Result:
The machine was not deleted and the server keeps saying `machine1 failed with: failed to get instance for machine machine1 after the delete got triggered`
The only way of getting out of this situation is to manually edit the machine's spec and remove finalizers.

In general the described state exists because we add finalizers to a machine before creating a node because we want to prevent deletion of a machine resource. 

As I can imagine that the call that requests a node can fail for many reasons, I think that this issue could help us track discussion on possible solutions to this issue.

**Comment by mrIncompetent** [comment]
Would it solve the problem when we add the finalizer directly after we successfully created the instance at the cloud provider?

Or we do a getInstance in the sync loop and add the finalizer as soon as we get an instance?
That way we would solve the problem when the Patch/Updated fails in the case above.

**Comment by p0lyn0mial** [comment]
> Would it solve the problem when we add the finalizer directly after we successfully created the instance at the cloud provider?

I think so, but then we introduce another issue - a user decided to delete `Machine` while we were making a call to "create an instance"

**Comment by alvaroaleman** [comment]
Noticed that issue some time ago as well. IMHO the approach of adding the finalizer after the first `getInstance` succeeded makes most sense.

If for whatever reason `getInstance` stops working later on (e.G. credentials got invalidated) then the user has to delete the finalizer manually to be able to delete the machine, but I think that is way better than risking to leave orphaned instances at the cloud provider.

**Comment by p0lyn0mial** [comment]
From a user perspective `orphaned` instances at cloud provider mean losing some money.Thus setting finalizers as we do at the moment seems to be good and prevents exactly that scenario.

In situation like the one described we will make use of `terminal` errors (defined in the spec) to indicate erroRs that have to be resolved manually.
