### ISSUE TITLE
CoreDNS crash loop on Flatcar 3227.2.0

### ISSUE THREAD

**Issue by jstremick** [kubermatic/machine-controller#1377]
As of Flatcar 3227.2.0 (which was released as an AMI on Jul 19 2022), CoreDNS gets stuck in a crash loop due to the underlying /etc/resolv.conf on nodes.

`[FATAL] plugin/loop: Loop (127.0.0.1:41860 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 6678297518826138904.7682940538006338517."`

This is due to the /etc/resolv.conf of the host being a symlink that points at /run/systemd/resolve/stub-resolv.conf which contains a nameserver entry for 127.0.0.53. Before Flatcar 3227.2.0, it was a symlink that pointed to /run/systemd/resolve/resolv.conf, which contains a nameserver entry with an IP local to this node's network.

I believe a fix is needed similar to what you're already doing for a couple OSs, like Ubuntu - https://github.com/kubermatic/machine-controller/blob/master/pkg/userdata/ubuntu/provider.go#L271 - where you override the default resolv.conf for kubelet and point it at the other location.

**Comment by kron4eg** [comment]
Thanks for the report, we will look into that.
