### ISSUE TITLE
KubeVirt: Conflict with Secondary Disk naming

### ISSUE THREAD

**Issue by sankalp-r** [kubermatic/machine-controller#1378]
Secondary Disk for kubevirt VM has a naming pattern like `secondarydisk0`, `secondarydisk1`.
After scaling the Machine deployment, all the VMs will try to create secondary disks with the same naming pattern resulting in a conflict and some VMs doesn't work.

**Comment by mfranczy** [comment]
this issue will be closed once the fix lands in KKP 2.21
