### ISSUE TITLE
Support Ubuntu 22.04 in Machine Controller

### ISSUE THREAD

**Issue by mfahlandt** [kubermatic/machine-controller#1394]
Description of the feature you would like to add / User story
As Ubuntu 22.04 is the new LTS Version of Ubuntu we should also support this as an OS. 
KKP and KubeOne rely on the support in MC, to make this a supported OS in those projects we need the support in MC.

Solution details
Support Ubuntu 22.04 as OS in machine controller

Related issues:
https://github.com/kubermatic/kubeone/issues/2223
https://github.com/kubermatic/kubermatic/issues/10669
https://github.com/kubermatic/operating-system-manager/issues/197

**Comment by wszychta** [comment]
I also would like to see support for Ubuntu 22.04
