### ISSUE TITLE
Support for Kubernetes 1.25

### ISSUE THREAD

**Issue by embik** [kubermatic/machine-controller#1418]
Kubernetes 1.25.0 is [out now](https://groups.google.com/a/kubernetes.io/g/dev/c/b_bqutVwRdk/m/0IrkGP9XBAAJ). We should look into what is required to support it in machine-controller. Also see [the changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#changelog-since-v1240).

Consider this issue a placeholder and please feel free to update it with findings/considerations.

Key considerations:

- cgroupv2 support graduates (probably also affects OSM)
- SeccompDefault promoted to beta (should be we enable this on the MC side?)
- TBD?

**Comment by ahmedwaleedmalik** [comment]
@embik I think this is already done. Maybe we can close this?

**Comment by embik** [comment]
Since #1474 added tests for 1.25, I would say yes.
