### ISSUE TITLE
Machines are not created

### ISSUE THREAD

**Issue by AhmedMozaly** [kubermatic/machine-controller#1538]
I've deployed custom controller to GKE cluster 
Machines are created on k8s cluster but not actually created on GCP

When I ran something like `kubectl -n kube-system describe machine gce-machinedeployment-687fdbd858-wzlvl `
It says that's, Secret "gce-machinedeployment-kube-system-provisioning-config" not found
Although I've created this secret manually but still the error says that it's not found

Any thoughts for the reason?
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/781863/214193530-190bcfa8-ba9e-4eaf-8deb-0cbb41a66030.png">

**Comment by embik** [comment]
Hi @AhmedMozaly, that sounds like operating-system-manager (OSM) is not installed. Can you verify you applied https://github.com/kubermatic/machine-controller/blob/main/examples/operating-system-manager.yaml to your cluster?

**Comment by AhmedMozaly** [comment]
Thanks @embik for the update 
It's already installed
<img width="833" alt="image" src="https://user-images.githubusercontent.com/781863/214240095-e9f9860a-92e6-4012-aab9-556ab9d86499.png">

But the strange thing is that  `kubectl -n kube-system get operatingsystemconfig` gets nothing, is that expected?

<img width="682" alt="image" src="https://user-images.githubusercontent.com/781863/214240275-19e83fb0-7cb9-42ab-9d3a-b8d65e25ab03.png">

**Comment by embik** [comment]
OSCs should be generated for your `MachineDeployments`, so this is surprising. Can you please check logs for the `operating-system-manager` Deployment and possibly share them? If the necessary secrets don't exist (regarding your initial point: those secrets are looked for in a special namespace, not `kube-system`), that seems to be an OSM problem.

**Comment by AhmedMozaly** [comment]
Running `kubectl -n kube-system logs operating-system-manager-746c7b6494-466gk`
Getting
`E0124 08:13:34.206307       1 reflector.go:140] k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:169: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:kube-system:operating-system-manager" cannot list resource "endpoints" in API group "" at the cluster scope`

**Comment by embik** [comment]
@ahmedwaleedmalik any idea what OSM is watching endpoints for? Looks like insufficient permissions in our `ClusterRole`.

**Comment by AhmedMozaly** [comment]
@@ahmedwaleedmalik could you kindly check if there is something here that I can review at my side?

**Comment by ahmedwaleedmalik** [comment]
> @@ahmedwaleedmalik could you kindly check if there is something here that I can review on my side?

Hi @AhmedMozaly, OSM doesn't need cluster-wide access for `endpoints` and the RBAC in [examples](https://github.com/kubermatic/machine-controller/blob/main/examples/operating-system-manager.yaml) should be sufficient. Let me try this locally.
