### ISSUE TITLE
Unreleased Features

### ISSUE THREAD

**Issue by lucakuendig** [kubermatic/machine-controller#1545]
Hi Team,

I recently created two pull requests which you allready merged and wanted to ask when they might be released?
https://github.com/kubermatic/machine-controller/pull/1476
https://github.com/kubermatic/machine-controller/pull/1471
 
Additionaly I wanted to ask if there is an easier way to contact you, as we are planning to use machine-controller and might have some features and ideas we would like to discuss with you.

Thanks & Best Regards
Luca

**Comment by embik** [comment]
Hi Luca,

We are planning to cut machine-controller releases soon (before end of February). You can join the Kubermatic Community Slack (there's a link [in our docs](https://docs.kubermatic.com/kubermatic/v2.21/how-to-contribute-to-kkp/#communication-channels)) if you want to reach out in a setting that's less formal than GitHub issues/discussions.

**Comment by ahmedwaleedmalik** [comment]
These features were released on 15th Feb as part of https://github.com/kubermatic/machine-controller/releases/tag/v1.56.0
