### ISSUE TITLE
bug/feat: cluster-autscaler

### ISSUE THREAD

**Issue by oliverbaehler** [kubermatic/machine-controller#1552]
Hi guys, thanks for the project. Love it!
I am currently trying to get cluster-autoscaler running with kubermatic machine-controller. But it seems there are some problems with the health check of nodes. The controller complains this:

```
...
W0203 11:19:16.037299       1 clusterstate.go:438] Failed to find readiness information for MachineDeployment/kube-system/nutanix-machinedeployment
W0203 11:19:16.037328       1 clusterstate.go:376] Failed to find readiness information for MachineDeployment/kube-system/nutanix-machinedeployment-test
...
Cluster-wide:
  Health:      Healthy (ready=4 unready=0 (resourceUnready=0) notStarted=0 longNotStarted=0 registered=4 longUnregistered=0)
               LastProbeTime:      2023-02-03 11:19:11.627452852 +0100 CET m=+42.183547677
               LastTransitionTime: 2023-02-03 11:18:57.199372797 +0100 CET m=+27.755467559
  ScaleUp:     NoActivity (ready=4 registered=4)
               LastProbeTime:      2023-02-03 11:19:11.627452852 +0100 CET m=+42.183547677
               LastTransitionTime: 2023-02-03 11:18:57.199372797 +0100 CET m=+27.755467559
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2023-02-03 11:19:11.627452852 +0100 CET m=+42.183547677
               LastTransitionTime: 2023-02-03 11:18:57.199372797 +0100 CET m=+27.755467559

NodeGroups:
  Name:        MachineDeployment/kube-system/nutanix-machinedeployment
  Health:      Unhealthy (ready=0 unready=0 (resourceUnready=0) notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=3 (minSize=3, maxSize=10))
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
  ScaleUp:     Backoff (ready=0 cloudProviderTarget=3)
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2023-02-03 11:19:11.627452852 +0100 CET m=+42.183547677
               LastTransitionTime: 2023-02-03 11:18:57.199372797 +0100 CET m=+27.755467559

  Name:        MachineDeployment/kube-system/nutanix-machinedeployment-test
  Health:      Unhealthy (ready=0 unready=0 (resourceUnready=0) notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=1 (minSize=3, maxSize=10))
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
  ScaleUp:     Backoff (ready=0 cloudProviderTarget=1)
               LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
               LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
  ScaleDown:   NoCandidates (candidates=0)
               LastProbeTime:      2023-02-03 11:19:11.627452852 +0100 CET m=+42.183547677
               LastTransitionTime: 2023-02-03 11:18:57.199372797 +0100 CET m=+27.755467559
```

It seems to understand, that 4 `Machines` are healthy as seen under **Cluster-wide**. But somehow it can't read the health of the MachineDeployments (Although it gets the desired replicas and the autoscaler annotations correctly). My current wild guess is that there's something wrong with getting the readiness information from Kubermatic's MachienDeployments (https://github.com/kubernetes/autoscaler/blob/ba3b2447203e877cf2d3596cc59c7ef10acf8d89/cluster-autoscaler/clusterstate/clusterstate.go#L574). But I will have a look if I can figure it out.

Just wondering if anyone else noticed this problem.

# Versions

`machine-controller`: v1.55.0
`kubernetes`: 1.25.0
`cluster-autoscaler`: 1.25.0

**Comment by ahmedwaleedmalik** [comment]
@oliverbaehler do the nodes have `providerID`? 

```
kubectl get nodes -o jsonpath={'.items..spec.providerID'}
```

Autoscaler, unfortunately, is dependent upon the `providerID` for the nodes. For Nutanix, since we don't have support for in-tree cloud provider or external CCM we are not able to determine the [providerID](https://github.com/kubermatic/machine-controller/blob/main/pkg/cloudprovider/provider/nutanix/provider.go#L91).

**Comment by oliverbaehler** [comment]
Exactly, both Machines and Nodes are missing the providerID field. I might need a bit more explenation but looking at the official nutanix provider they just combine `nutanix://` + vm.uuid (https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix/blob/e36d192043ae04a01778270b54098b698d1aa7a6/controllers/helpers.go#L92). So I guess the same could be applied here:

```
const (
	providerIdPrefix = "nutanix://"
)
...
func (nutanixServer Server) ProviderID() string {
	return fmt.Sprintf("%s%s", providerIdPrefix, nutanixServer.ID())
}
...
```
If manually patched `.spec.providerID` for both machine and nodes. The value is `nutanix://${vm.uuid}` for both machine and node. I guess just adding for the nodes would be enough. But with that cluster-autoscaler looks much more satisfied:

```
I0206 09:38:25.351153       1 clusterapi_provider.go:67] discovered node group: MachineDeployment/kube-system/nutanix-machinedeployment (min: 3, max: 10, replicas: 3)
I0206 09:38:25.352021       1 clusterapi_controller.go:553] node "nutanix-machinedeployment-5bc945cd59-5hwbg" is in nodegroup "MachineDeployment/kube-system/nutanix-machinedeployment"
I0206 09:38:25.352123       1 pre_filtering_processor.go:66] Skipping nutanix-machinedeployment-5bc945cd59-5hwbg - node group min size reached
I0206 09:38:25.356464       1 clusterapi_controller.go:553] node "nutanix-machinedeployment-5bc945cd59-l6t6l" is in nodegroup "MachineDeployment/kube-system/nutanix-machinedeployment"
I0206 09:38:25.356508       1 pre_filtering_processor.go:66] Skipping nutanix-machinedeployment-5bc945cd59-l6t6l - node group min size reached
I0206 09:38:25.356887       1 clusterapi_controller.go:553] node "nutanix-machinedeployment-5bc945cd59-s4dpq" is in nodegroup "MachineDeployment/kube-system/nutanix-machinedeployment"
I0206 09:38:25.356903       1 pre_filtering_processor.go:66] Skipping nutanix-machinedeployment-5bc945cd59-s4dpq - node group min size reached
I0206 09:38:25.356992       1 static_autoscaler.go:520] Scale down status: unneededOnly=false lastScaleUpTime=2023-02-06 08:00:49.892266892 +0100 CET m=-3582.119671006 lastScaleDownDeleteTime=2023-02-06 08:00:49.892266892 +0100 CET m=-3582.119671006 lastScaleDownFailTime=2023-02-06 08:00:49.892266892 +0100 CET m=-3582.119671006 scaleDownForbidden=false isDeleteInProgress=false scaleDownInCooldown=false
I0206 09:38:25.357123       1 static_autoscaler.go:533] Starting scale down
I0206 09:38:25.357377       1 clusterapi_provider.go:67] discovered node group: MachineDeployment/kube-system/nutanix-machinedeployment (min: 3, max: 10, replicas: 3)
I0206 09:38:25.357430       1 scale_down.go:918] No candidates for scale down
I0206 09:38:25.357602       1 clusterapi_provider.go:67] discovered node group: MachineDeployment/kube-system/nutanix-machinedeployment (min: 3, max: 10, replicas: 3)

...

    Cluster-autoscaler status at 2023-02-06 09:30:04.062973252 +0100 CET:
    Cluster-wide:
      Health:      Healthy (ready=3 unready=0 notStarted=0 longNotStarted=0 registered=3 longUnregistered=0)
                   LastProbeTime:      2023-02-06 09:30:04.055666664 +0100 CET m=+1772.043728872
                   LastTransitionTime: 2023-02-06 09:00:59.893701312 +0100 CET m=+27.881763401
      ScaleUp:     NoActivity (ready=3 registered=3)
                   LastProbeTime:      2023-02-06 09:30:04.055666664 +0100 CET m=+1772.043728872
                   LastTransitionTime: 2023-02-06 09:00:59.893701312 +0100 CET m=+27.881763401
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2023-02-06 09:30:04.055666664 +0100 CET m=+1772.043728872
                   LastTransitionTime: 2023-02-06 09:00:59.893701312 +0100 CET m=+27.881763401

    NodeGroups:
      Name:        MachineDeployment/kube-system/nutanix-machinedeployment
      Health:      Healthy (ready=3 unready=0 notStarted=0 longNotStarted=0 registered=3 longUnregistered=0 cloudProviderTarget=3 (minSize=3, maxSize=10))
                   LastProbeTime:      2023-02-06 09:30:04.055666664 +0100 CET m=+1772.043728872
                   LastTransitionTime: 2023-02-06 09:14:21.675110414 +0100 CET m=+829.663172508
      ScaleUp:     NoActivity (ready=3 cloudProviderTarget=3)
                   LastProbeTime:      2023-02-06 09:30:04.055666664 +0100 CET m=+1772.043728872
                   LastTransitionTime: 2023-02-06 09:14:21.675110414 +0100 CET m=+829.663172508
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2023-02-06 09:30:04.055666664 +0100 CET m=+1772.043728872
                   LastTransitionTime: 2023-02-06 09:00:59.893701312 +0100 CET m=+27.881763401
```

Maybe I am also jsut misudnerstanding things.. wdyt? :D

**Comment by ahmedwaleedmalik** [comment]
> So I guess the same could be applied here

Yes, you are right. Unfortunately, we couldn't test this with the CCM for Nutanix to determine this.

> So is the intention from the machine-controller to not support this at all

We are definitely going to add this. a

**Comment by ahmedwaleedmalik** [comment]
With https://github.com/kubermatic/machine-controller/pull/1568 we have added the `providerID` for Nutanix. Autoscaling should work fine for Nutanix now 🚀 

Maybe we can close this ticket now? :)

**Comment by oliverbaehler** [comment]
Thanks for the quickfix @ahmedwaleedmalik. If it's okay I will do some testing the coming days just to verify its working with nutanix. I ll comment again

**Comment by ahmedwaleedmalik** [comment]
> If it's okay I will do some testing the coming days just to verify its working with nutanix

That's even better and would be really helpful for us. But please do keep in mind that these are unreleased changes as of now so you might have to build your own image for machine-controller.

**Comment by oliverbaehler** [comment]
Hi @ahmedwaleedmalik 

I am not sure if I am missing something. But I tested with the current master and the behavior is still the same. The machine object does not have a `ProviderID` field, the node object is also still missing `ProviderID` so the status is quo.

Is there even the logic in the machine-controller to annotate the machines/nodes?. Status still the same:

```
    NodeGroups:
      Name:        MachineDeployment/kube-system/dev-olb-workers
      Health:      Unhealthy (ready=0 unready=0 notStarted=0 longNotStarted=0 registered=0 longUnregistered=0 cloudProviderTarget=3 (minSize=3, maxSize=10))
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleUp:     Backoff (ready=0 cloudProviderTarget=3)
                   LastProbeTime:      0001-01-01 00:00:00 +0000 UTC
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2023-03-03 16:48:24.758452978 +0100 CET m=+779.550107568
                   LastTransitionTime: 2023-03-03 16:35:53.080457674 +0100 CET m=+27.872112283
```

WDYT?

**Comment by LittleFox94** [comment]
I can see PRs like #1568, but cannot find any place in the code where the `Machine.Spec.ProviderID` attribute is actually set based on the result of that call and all machines I'm looking at rn don't have that attribute set - so it seems to not be a problem with my code-reading abilities; am I missing something?

**Comment by ahmedwaleedmalik** [comment]
> I can see PRs like #1568, but cannot find any place in the code where the `Machine.Spec.ProviderID` attribute is actually set based on the result of that call and all machines I'm looking at rn don't have that attribute set - so it seems to not be a problem with my code-reading abilities; am I missing something?

Machine-controller doesn't configure the `ProviderID` and in turn, it relies on the in-tree or out-of-tree(external) CCMs to take care of configuring the providerID for the "nodes". Regarding #1568, we use providerID internally [here](https://github.com/kubermatic/machine-controller/blob/release/v1.57/pkg/controller/machine/controller.go#L1167) and maybe in a few other places.

**Comment by LittleFox94** [comment]
I mean't in the Machine object though, not in the Node obejct

**Comment by ahmedwaleedmalik** [comment]
> it relies on the in-tree or out-of-tree(external) CCMs to take care of configuring the providerID for the "nodes"

On the "nodes", we keep the providerID in the machine spec as empty, it's not really used anywhere.

**Comment by ahmedwaleedmalik** [comment]
But that's going to change against this ticket. We just started working on that, as you saw in the [OSM PR](https://github.com/kubermatic/operating-system-manager/pull/323) as well. The idea is that when in-tree or external CCM are not available only then machine-controller/OSM should take care of configuring the provider ID for the nodes/machines.

**Comment by LittleFox94** [comment]
> > it relies on the in-tree or out-of-tree(external) CCMs to take care of configuring the providerID for the "nodes"
> 
> On the "nodes", we keep the providerID in the machine spec as empty, it's not really used anywhere.

I can see several places in cluster-autoscaler where it wants to use the ProviderID of the Machine as well, e.g. here https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go#L601

**Comment by ahmedwaleedmalik** [comment]
> I can see several places in cluster-autoscaler where it wants to use the ProviderID of the Machine as well, e.g. here https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go#L601

I was talking about machine-controller here. We don't really use it anywhere "within" machine-controller.

**Comment by oliverbaehler** [comment]
Thanks @ahmedwaleedmalik, we ll retest :))
