### ISSUE TITLE
Add support for Disk Size for Scaleway

### ISSUE THREAD

**Issue by lakshmanpasala** [kubermatic/machine-controller#1567]
Currently there is no way to add the disk size or type for the Scaleway provider. Not sure why this wasn't done from the beginning as every other supported provider has this.

**Comment by ahmedwaleedmalik** [comment]
> Not sure why this wasn't done from the beginning as every other supported provider has this.

The support for Scaleway has added around 2 years ago and a lot has changed since then.

@lakshmanpasala we are always open for contributions, would you like to implement this?

**Comment by lakshmanpasala** [comment]
Sure. Let me pick this up.
