### ISSUE TITLE
Vsphere - vmNetName parameter prevents any VMs from getting created

### ISSUE THREAD

**Issue by dharapvj** [kubermatic/machine-controller#1599]
Currently, if we do __not__ specify `vmNetName` parameter in the machine-controller configuration (as part of KKP user-cluster config), the cloned vm inherits network configured on the template VM and works fine.

We would like to use one common template VM to create VMs which are using different networks. So if we specify vmNetName in configuration (specifically in KKP Preset), machine-controller stops VM creation, even after providing administrator permissions on the user.

The error is also quite misleading..
```
E0324 06:39:26.978095       1 machine_controller.go:383] Failed to reconcile machine "tt2-6cf86694b4-gnf7l": An error of type = InvalidConfiguration, with message = failed to create cloned vm: 'failed to reconfigure the VM: ServerFaultCode: Permission to perform this operation was denied.' occurred
```
I see that some such related work as done as part of https://github.com/kubermatic/machine-controller/pull/613/ earlier... but I could not understand if that is breaking this.

**Comment by embik** [comment]
What MC / KKP version does this happen on for you?

**Comment by dharapvj** [comment]
It was clarified that the Network --> Assign request was missing on the target network (even though it was present at DVS with propagate=true). Not sure why it does not get propagated.

Adding the permission explicitly to Network resolved the issue.

/close
