### ISSUE TITLE
E2E taking too long to run

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#161]
At the moment running the complete test suite takes ~1h. This prevents us from running the test suite on "pull request" basis. 

We would like to take a deeper look into this and hopefully improve test time as much as possible. 

the completed runs:
https://circleci.com/gh/kubermatic/machine-controller/2738

**Comment by p0lyn0mial** [comment]
for reference see also:
#159
#129

**Comment by alvaroaleman** [comment]
Closing, as this got fixed within #159
