### ISSUE TITLE
Fix VCD tests

### ISSUE THREAD

**Issue by xrstf** [kubermatic/machine-controller#1619]
VCD e2e tests are currently failing with

> Error: 400: [ a0acf93e-1c9e-4543-87ba-2e9a4585ebfa ] The entity Ref: com.vmware.vcloud.entity.vapp:6602ebbd-4b07-4aad-9909-022fad2e8efe is busy completing an operation VDC_RECOMPOSE_VAPP."}
2023-04-19T18:29:11.592Z	error	machine-controller	machine/controller.go:402	Reconciling failed	{"machine": "kube-system/ubuntu-1-26-1-vcd-1648753846731673600-5889b9cd

See for example #1606

**Comment by ahmedwaleedmalik** [comment]
@csengerszabo maybe after KKP 2.26 release we can get this prioritized somehow. It's not something urgent but would be great if we can get rid of the flakes/failures.
