### ISSUE TITLE
Vsphere E2E tests

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#162]
Add the following test cases to the existing E2E test suite.

```
Ubuntu + Docker 1.13
Ubuntu + Docker 17.03
Ubuntu + CRI-O 1.9
```

Clean up `.circle/config.yaml`, so that it doesn't run the test using `create-and-destroy-machine.sh` script

**Comment by p0lyn0mial** [comment]
for reference see also:
#159
#129

**Comment by p0lyn0mial** [comment]
@alvaroaleman @mrIncompetent PTAL at the test cases.

**Comment by mrIncompetent** [comment]
sgtm

**Comment by alvaroaleman** [comment]
I am not sure if we must test every OS and containerruntimeversion combination on every provider. I think its enough if we have one suite that tests every supported distribution on every provider with a single container runtime only (here: Test Ubuntu+Docker works on vsphere) and a distinct suite that tests all possible distribution and containerrumtime configurations on one cloud provider.

**Comment by mrIncompetent** [comment]
I would prefer testing almost all possible combinations.
We have some specials logic when using Docker 1.12 or 17.03. Also CRI-O is a very special case on its own.
Also providers might differ in operating system images. Something we should test.

And as long as we can run all of those tests in parallel why not?
