### ISSUE TITLE
OpenStack 1.26 tests do not work, likely due to CCM limitations

### ISSUE THREAD

**Issue by embik** [kubermatic/machine-controller#1620]
The OpenStack e2e tests fail, most likely since testing 1.26 nodes. The reason for that is that the CCM is missing, so nodes never get initialised properly. At least that is my understanding. Someone needs to investigate this further.

**Comment by ahmedwaleedmalik** [comment]
Is being tracked by https://github.com/kubermatic/machine-controller/issues/1626
