### ISSUE TITLE
Schedule E2E night tests run

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#164]
Since running the complete e2e suite takes too long, as a temporary step we could schedule a night tests run. Running the test frequently would increase confidence and hopefully would reveal potential issues that might crop up.

**Comment by p0lyn0mial** [comment]
for reference see also:
#159
#129

**Comment by p0lyn0mial** [comment]
@alvaroaleman @mrIncompetent PTAL

**Comment by mrIncompetent** [comment]
Is this something we can do with circle CI?
Afaik it only supports builds on push.

Or do we need a Jenkins now?

**Comment by p0lyn0mial** [comment]
yes, `CircleCI` supports this
https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow

**Comment by alvaroaleman** [comment]
Closing as wontfix, since we managed to speed up the e2e tests sufficiently fast :)
