### ISSUE TITLE
Test and document centos on vsphere

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#166]
As a user I want to be able to spin up worker nodes on vsphere that use CentOS as distribution.

*Acceptance criteria:*

* There is a documentation on how to import/create a suitable image for centos on vsphere
* An image in our vsphere test cluster was created by following the steps documented
* The e2e tests are extended to also test CentOS on vsphere

**Comment by pkavajin** [comment]
@pkavajin  @alvaroaleman please write what this issue is about.

**Comment by alvaroaleman** [comment]
@pkavajin Updated the description. Is it sufficent now?

**Comment by pkavajin** [comment]
@alvaroaleman regarding "There is a documentation on how to import/create a suitable image for centos on vsphere" is there already some documentation for e.g. ubuntu or sth to have a look at? Beside that, it looks fine for me, ty :-)

**Comment by alvaroaleman** [comment]
Yeah, there is a minimal doc that just contains Ubuntu instructions: https://github.com/kubermatic/machine-controller/blob/5c11b45346a6e22b6a3a0538a3d568c48da342bc/docs/vsphere.md#vmwware-vsphere
