### ISSUE TITLE
Enable setting metadata on openstack instances

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#169]
It should be possible to set the metadata on a openstack instance via a machine.yaml

Very similar to the tags in AWS

**Comment by p0lyn0mial** [comment]
do we want to normalise the tags ? for instance convert them to lowercase ?

the tags are user owned, so I'm not sure how much we want/can interfere.

**Comment by mrIncompetent** [comment]
> do we want to normalise the tags ? for instance convert them to lowercase ?

I would leave them how they are for now. If we encounter issues with this we'll add it.

> the tags are user owned, so I'm not sure how much we want/can interfere.

Not sure what you mean with this

**Comment by p0lyn0mial** [comment]
>the tags are user owned, so I'm not sure how much we want/can interfere.

the tags are defined by the end user. I believe the user has good reasons to provide the tags so changing them might be confusing.
