### ISSUE TITLE
Deterministic way to get private ip of machine

### ISSUE THREAD

**Issue by 2000yeshu** [kubermatic/machine-controller#1702]
We are currently fetching the default ip address of a machine using 
```
ip -o route get 1 | grep -oP "src \K\S+"
```
to be set as the `node-ip` for kubelet.
Some cloud provider like vultr set the public address as the default address as a result of which k8s components see the public address of the machine as the private ip and the status subresource of the node also suffers that mismatch.
I think we need a more deterministic way to find out the private ip of the machine.

**Comment by embik** [comment]
Hi @2000yeshu, just as a heads up - Vultr is considered a [community provider](https://github.com/kubermatic/machine-controller?tab=readme-ov-file#community-providers), so the machine-controller team cannot test against it or verify that it works properly. We welcome contributions to improve support for it, but I'm not aware of any other cloud provider having issues with the current way to determine IP addresses.

**Comment by 2000yeshu** [comment]
Ok, thanks
