### ISSUE TITLE
Node not ready due to cloud provider instance network issues

### ISSUE THREAD

**Issue by 2000yeshu** [kubermatic/machine-controller#1708]
This is not an issue with the machine controller but a good to have for bypassing node uptime maintenance.
In my vultr cluster, sometimes the instance network becomes unreachable because of which the node goes into Unknown status as kubelet stops responding. This happens randomly so I have been running a hack wherein I have given a certain timeout to the controller wherein if the node is not Ready state for this time period judging by the last heartbeat time, I delete the machine which in turn triggers the machine-set to create a new machine.
I was wondering if this belongs as an optional parameter for the GA machine controller as well.

**Comment by embik** [comment]
This sounds like a dedicated controller loop, so I would maybe recommend to drop this into a small independent controller you can deploy as its own container. I have never heard of permanent network issues that can only be resolved by deleting the node, so I'm not sure how useful it would be in machine-controller.

**Comment by 2000yeshu** [comment]
Yeah aligned here. Vultr SLAs are pretty bad. Anything specific to a cloud provider should be a custom solution. I will close the issue
