### ISSUE TITLE
Concurrency issues when creating secret in e2e tests

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#173]
Right now the e2e tests sometimes fail due to `kubectl` trying to create the secret when its already there

e.G. https://circleci.com/gh/kubermatic/machine-controller/2877?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

We should probably just not use a secret in the e2e tests and instead just put the required credentials into the machine spec.

**Comment by p0lyn0mial** [comment]
https://github.com/kubermatic/machine-controller/pull/175
