### ISSUE TITLE
e2e tests modify manifest by providing a field selector

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#178]
At the moment tests replace desired fields in the manifest based on string matching. For example:

```
params = fmt.Sprintf("%s,<< MACHINE_NAME >>=%s,<< NODE_NAME >>=%s", params, machineName, nodeName)
params = fmt.Sprintf("%s,<< OS_NAME >>=%s,<< CONTAINER_RUNTIME >>=%s,<< CONTAINER_RUNTIME_VERSION >>=%s", params, testCase.osName, testCase.containerRuntime, testCase.containerRuntimeVersion)

```

we would like to change that by providing the field path for example `spec.providerConfig. cloudProvider`. this would not only look better but would also allow to consume manifest under `example` directory.

**Comment by kdomanski** [comment]
@p0lyn0mial So you basically mean switching to use Go templates, do I understand correctly?

**Comment by p0lyn0mial** [comment]
instead of replacing a string with the given name `<< MACHINE_NAME >>` in the manifest, I think it would nice if we could replace the value by providing a field selector for example `spec.providerConfig.cloudprovider`
