### ISSUE TITLE
Support Flatcar Linux on Hetzner Cloud

### ISSUE THREAD

**Issue by P4sca1** [kubermatic/machine-controller#1817]
As a Hetzner Cloud user
I would like to deploy worker nodes using the Flatcar Linux operating system. I already run my control plane using Flatcar on Hetzner Cloud (both ARM and x86) successfully.

Official Flatcar docs for Hetzner: https://www.flatcar.org/docs/latest/installing/cloud/hetzner/

Hetzner support is currently only available on the beta channel, and not in the stable channel.

Hetzner cloud does not provide a default image for Flatcar, however it is possible to create a snapshot for Flatcar Linux manually, which can be used as an image when creating new servers.

For initial beta support, it would be great if kubeone allows the operatingSystem: flatcar annotation for Hetzner worker nodes, as long as a custom image is provided. The user would be responsible for creating the Flatcar Linux snapshot in Hetzner Cloud.

**Comment by kron4eg** [comment]
Issue transferred to machine-controller repo.

**Comment by ahmedwaleedmalik** [comment]
@P4sca1 can we close this now that https://github.com/kubermatic/machine-controller/pull/1818 has been merged?

**Comment by P4sca1** [comment]
Yes, we can open a new issue once Hetzner adds official images for Flatcar Linux.
