### ISSUE TITLE
Upstream: MachineSet controller sets MachineSetStatus

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#196]
The current implementation of MachineSet controller doesn't set MachineSetStatus at all. This item tracks potential implementation.

For reference implementations see:

https://github.com/kubernetes/kubernetes/blob/a0844c17bfb964e3d1709784203e8404f790116c/pkg/controller/replicaset/replica_set_utils.go#L35:1

https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/machineset.go#L518

Upstream issue: https://github.com/kubernetes-sigs/cluster-api/issues/54#issuecomment-380945873

**Comment by alvaroaleman** [comment]
This was implemented upstream, see https://github.com/kubernetes-sigs/cluster-api/issues/54
