### ISSUE TITLE
Upstream: MachineSet controller listens for Machine resources

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#197]
The current implementation of MachineSet controller watches only the desired state of the cluster. This approach is not sufficient as there are other actors in the system that can easily change the current state (e.g. delete/add a Machine) of the cluster. Thus adding event handlers for Machines to our MachineSet along with appropriate handlers (requeue) seems to be valid approach.

Upstream issue: https://github.com/kubernetes-sigs/cluster-api/issues/53

**Comment by mrIncompetent** [comment]
During the kubecon cluster-api meeting folks from VMWare aggreed to upstream their MachineSet & MachineDeployment controller

**Comment by alvaroaleman** [comment]
This was implemented upstream, see https://github.com/kubernetes-sigs/cluster-api/issues/53
