### ISSUE TITLE
Add support for Red Hat Enterprise Linux

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#205]

**Comment by alvaroaleman** [comment]
What is missing for this to work? I think ppl should be able to use centos operating system with a rhel image

**Comment by mrIncompetent** [comment]
What i had in mind was the RHEL subscription.
But as RHEL is only available on vSphere and AWS, prebaked images should be the way to go.
As operating system CentOS should be used. (On AWS the AMI needs to be specified)
