### ISSUE TITLE
Enable enableUUID option for all vSphere machines

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#206]
Possible via commandline:
```
./govc_linux_amd64 vm.change -e="disk.enableUUID=1" -vm /Datacenter/vm/new-test-seed/worker-2
```

See https://storagehub.vmware.com/export_to_pdf/kubernetes-vsphere-cloud-provider section Enable disk UUID on Node virtual machines

**Comment by kdomanski** [comment]
Blocked by #203

**Comment by kdomanski** [comment]
@mrIncompetent This is already handled by https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/vsphere/helper.go#L130
The issue is present only in machines provisioned by hand.
