### ISSUE TITLE
[Ubuntu] Make source for external dependencies configurable

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#208]
We currently download some dependencies from the internet when provisioning an Ubuntu machine.
We need to be able to configure the source for all of those dependencies.
This should probably be configurable withing the Ubuntu-OperatingSystemSpec.

We depend on the following binaries which come from external sources:
- kubelet
- kubeadm
- cni-plugins
- kubeadm systemd config `10-kubeadm.conf`
- crictl

Also what we need to cover within this issue:
- If a dependency already exists, skip loading it from the external source.
This enables us to use prebuild-images which already contain all of those dependencies.

**Comment by mrIncompetent** [comment]
@alvaroaleman do we need to configure other APT repositories as well?

**Comment by alvaroaleman** [comment]
Both docker and cri-o come from third-party repos, so that needs to be set up.

**Comment by mrIncompetent** [comment]
Where do we draw the line between something that needs to exist already on the image and the sources we configure?

**Comment by alvaroaleman** [comment]
Thinking about this whole issue some more, we should probably not even attempt to make this configurable but instead spend the time on writing some scripts that prebuild the images for different scenarios (distro, docker/crio version, k8s version). The same goes for the hyperkube image, instead of making the location configurable we could put it into the coreos os image.

WDYT @mrIncompetent @p0lyn0mial?

**Comment by mrIncompetent** [comment]
Prebaking images seem like a very sane solution. It would make the setup around the machine-controller simpler. (no repositories & no binaries hosted somewhere)
Though we still need to adjust our code to not download dependencies when they already exist, right?

LGTM

**Comment by alvaroaleman** [comment]
There is some minor stuff like the ubuntu bootcmd but almost everything we currently have should work in an offline environment when all binaries and pacakges are already present

**Comment by mrIncompetent** [comment]
Closed in favor of https://github.com/kubermatic/machine-controller/issues/212

**Comment by p0lyn0mial** [comment]
I really like the idea of having self-sufficient images.

lgtm
