### ISSUE TITLE
[Coreos] Hyperkube image needs to be configurable

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#209]
Currently we use the default image for the kubelet-wrapper script.
This points to quay.io

Via the ContainerLinux-OperatingSystemSpec it should be possible to override the image. Image & Tag should be individual fields

**Comment by alvaroaleman** [comment]
Mmh. I would prefer to just make the `registry` configurable on the machine-controller, as this is an environment-specific setting and I think there is little chance people want it to be different on one machine but not on another one, assuming both are managed by the same machine-controller.


Related: We may have to think about passing in authentication to private registries for pulling the `hyperkube` image

**Comment by mrIncompetent** [comment]
I'm not sure if we should set it globally. It would mean a flag, right?
Being able to specify a custom image via manifest seems common. See etcd-operator & prometheus-operator.

**Comment by alvaroaleman** [comment]
Yeah, but we should stay consistent in what we do. This would mean to either:

* Make both the hyperkube image and a download url for k8s binaries configurable inside the machines
* Make those two configurable on the `machine-controller`

**Comment by mrIncompetent** [comment]
I would prefer the way via the Machine Manifest.
As you are the owner, you are free to choose :)
If decided, please update the issues!

**Comment by mrIncompetent** [comment]
Closed in favor of https://github.com/kubermatic/machine-controller/issues/212
