### ISSUE TITLE
[Documentation] Create offline os images

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#212]
The documentation needs to cover the following topics
- Installation of required tools
- Creation of RHEL/Centos images
- Creation of Ubuntu images
- Creation of CoreOS images
- Usage of those images in vSphere

**Comment by kdomanski** [comment]
Just documenting the process of their creation, implies that people are supposed to follow the docs and create the images themselves whenever they need them. Wouldn't it be more productive to create a repo and a build job to generate these automatically and upload them to storage?

**Comment by kdomanski** [comment]
I'd split the "creation" part into separate stories for each of the OS images, leaving only their usage as a documentation story.

**Comment by mrIncompetent** [comment]
Pinging @alvaroaleman as he's the person interested in this topic

**Comment by alvaroaleman** [comment]
Not sure if this is big enough of a task to split it into dedicated issues.

The idea is to

* Have in this repo some scripting to build the images and get them into the platform of choice
* Document how to use that scripting

**Comment by kdomanski** [comment]
I get the idea, but I'm questioning it for the following reasons:
 * building the images is somewhat more complicated than "some scripting" and will be radically different for different target OS
 * different target platforms will typically require different image formats (but I assume the offline install is relevant mostly for vsphere)
 * doing this by hand will be a pain

**Comment by alvaroaleman** [comment]
> building the images is somewhat more complicated than "some scripting" and will be radically different for different target OS

Is it?  What we ultimatively need is a script for each distro (CoreOS, Ubuntu, CentOS/RHEL) that can take a kubernetes version and a container runtime type + version as input and then installs kubelet, kubeadm and the given container runtime. 

> different target platforms will typically require different image formats (but I assume the offline install is relevant mostly for vsphere

We should leverage [packer](https://www.packer.io/docs/builders/index.html) for that, it can output images to different providers
