### ISSUE TITLE
Machine with invalid cloud provider spec can never be deleted

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/machine-controller#224]
A `Machine` object added with invalid or missing cloud provider access credentials will still have its finalizer added, which upon deletion will fail forever in a loop.

For example adding a `Machine` with `cloudProvider: "vsphere"` but missing `vsphereURL` will naturally fail to create properly, but attempting to delete the object will result in infinite
`machine1 failed with: failed to get instance for machine machine1 after the delete got triggered, due to failed to get vsphere client: 'Post /sdk: unsupported protocol scheme ""'`

**Comment by p0lyn0mial** [comment]
Perhaps the only sane way is to not storing invalid machines. Rejecting the request would give immediate feedback to the user. I think this is something that was originally proposed by @alvaro and provoked a discussion we were having some time ago. (`webhook`)

I think this also account for scenarios like "changing existing configuration, be it credentials, end points". Any change made to machines has to pass admission.

**Comment by mrIncompetent** [comment]
Though a validation webhook should make this cleaner, the fact that we create the finalizer though no vSphere url was specified is an error we should fix.
And this does not require a webhook.

**Comment by alvaroaleman** [comment]
> Though a validation webhook should make this cleaner, the fact that we create the finalizer though no vSphere url was specified is an error we should fix.

We currently set the finalizer before validating the machine, I've created #243 to fix that
