### ISSUE TITLE
Implement admission controller for validation and defaulting

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#227]

**Comment by p0lyn0mial** [comment]
related issue #224

**Comment by p0lyn0mial** [comment]
this admission controller should be implemented as a webhook.
See https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks

the API server that actually accepts/stores `machines` resources will make use of the webhook

**Comment by mrIncompetent** [comment]
@alvaroaleman please provide your example code

**Comment by alvaroaleman** [comment]
Here is an example mutating admission webhook: https://github.com/alvaroaleman/k8s-auth-injector
