### ISSUE TITLE
e2e tests wait for a node to get deleted, instead of a machine

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/machine-controller#232]
https://github.com/kubermatic/machine-controller/blob/205c8975a692ed2203067b2186a1af806fbe02d4/test/e2e/provisioning/verify.go#L186
The test proceeds as soon as it cannot find a node associated with a machine. For slow running tests that means that the test will exit before the machine is actually deleted, potentially causing the machines to make it alive to the cleanup step.
cc @alvaroaleman

**Comment by mrIncompetent** [comment]
Does this mean the `Node` objects gets deleted before the machine?

If so, this is something we need to fix because a `Node` normally gets deleted via the garbage-collection from Kubernetes. A Node has a `OwnerReference` set to the `Machine` object. So when the `Machine` gets deleted the `Node` will be cleaned up afterwards as well.

**Comment by kdomanski** [comment]
It seems that either the Node gets removed before the machine or the owner reference is removed early. If you look at the build https://circleci.com/gh/kubermatic/machine-controller/4194
The E2E test step `Clean up machines` says:
```
machine.machine.k8s.io "scenario-2-ubuntu-docker-17-03-azure-4244" deleted
machine.machine.k8s.io "scenario-5-coreos-docker-1-13-azure-4244" deleted
machine.machine.k8s.io "scenario-6-coreos-docker-17-03-azure-4244" deleted
```
The machines should have been deleted in the previous step. Thus it seems that `assureNodeForMachine` poll loop returned while the machine object was still there.

**Comment by mrIncompetent** [comment]
Pinging @alvaroaleman as i'm not into e2e tests

**Comment by alvaroaleman** [comment]
I am really confused as to why this can happen. The only idea I can come up with is maybe the cloud-provider deleting the node when the instance gets deleted?

I'll work around this by ensuring both the machine and the node are gone
