### ISSUE TITLE
Extend e2e testing to different kubernetes versions

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#254]
We currently run e2e tests only against one Kubernetes version, 1.9.6. Changing this requires adjustments in the test suite, because CRI-O versions are only compatible with exactly one Kubernetes version and we have a test that has a hardcoded Cri-O 1.9 version in  it.

AC:

* We have at least one test for Kube versions 1.8, 1.9, 1.10, 1.11

**Comment by mrIncompetent** [comment]
Are we talking about the version of the complete Cluster or just the nodes?

**Comment by alvaroaleman** [comment]
Just the nodes
