### ISSUE TITLE
kube-bench kubelet issues

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/machine-controller#258]
* [ ] --allow-privileged argument is set to false
* [ ] --anonymous-auth argument is set to false
* [ ] --read-only-port argument is set to 0
* [ ] --streaming-connection-idle-timeout argument is not set to 0
* [ ] --protect-kernel-defaults argument is set to true
* [ ] --make-iptables-util-chains argument is set to true
* [ ] --keep-terminated-pod-volumes argument is set to false
* [ ] --hostname-override argument is not set
* [ ] --event-qps argument is set to 0
* [ ] --tls-cert-file and --tls-private-key-file arguments are set as appropriate
* [ ] RotateKubeletClientCertificate argument is set to true
* [ ] RotateKubeletServerCertificate argument is set to true

**Comment by mrIncompetent** [comment]
> --allow-privileged argument is set to false

This will break all clusters as we run Canal as Daemonset.

> --anonymous-auth argument is set to false

Needed for the kubeadm discovery.

**Comment by mrIncompetent** [comment]
@alvaroaleman PTAL

**Comment by alvaroaleman** [comment]
All the flags we set come from `kubeadm`, I do not really feel comfortable changing them if I am not sure what the effect is. Also there are a couple we must have:

>  --allow-privileged argument is set to false
Aside from canal this may also break other workloads ppl expect to work

>  --protect-kernel-defaults
Not sure if this will maybe break CentOS?

> --hostname-override
We introduced this to avoid problems with the cloud provider integration

**Comment by kdomanski** [comment]
This should probably be split into smaller stories that address specifics of each option.

**Comment by mrIncompetent** [comment]
I think we agreed at some point on not fixing those warnings as kube-bench was deprecated and the only useful warning was the `read-only-port`.

Correct me if i'm wrong @kron4eg @alvaroaleman

**Comment by kron4eg** [comment]
@mrIncompetent totally correct.
