### ISSUE TITLE
kube-bench config files issues

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/machine-controller#259]
After running kube-bench against a kubermatic cluster it reported some bad file permissions.

* [ ] kubelet.conf file permissions are set to 644 or more restrictive
* [ ] kubelet.conf file ownership is set to root:root
* [ ] kubelet service file permissions are set to 644 or more restrictive
* [ ] kubelet service file ownership is set to root:root
* [ ] proxy kubeconfig file permissions are set to 644 or more restrictive
* [ ] proxy kubeconfig file ownership is set to root:root
* [ ] certificate authorities file permissions are set to 644 or more restrictive
* [ ] client certificate authorities file ownership is set to root:root

This ticket should focus on fixing the file permissions for which the controller is responsible but not for files kubeadm/kubelet creates.

**Comment by pkavajin** [comment]
@mrIncompetent please specify what is kubeadm and what is our job.

**Comment by mrIncompetent** [comment]
Our responsibility:
-  kubelet service file

cc @alvaroaleman

**Comment by alvaroaleman** [comment]
This got fixed within #268 when moving to package-based installation.
