### ISSUE TITLE
how to point two networks for openstack machine?

### ISSUE THREAD

**Issue by lbvffvbl** [kubermatic/machine-controller#263]
Hi, is there any possibility to add instance with two networks for openstack machine? (Private and publick)

**Comment by alvaroaleman** [comment]
Hello @lbvffvbl 

An instance can only have exactly one `network` and `subnet`, if you want the instance to be publicly reachable you should set `floatingIpPool` to a Floating IP pool.

Does that answer your question?

**Comment by lbvffvbl** [comment]
We use INAP provider. and they haven't floating ip pool. only fixed ip - two networks public and private

**Comment by alvaroaleman** [comment]
I see. Well, we currently do not support that. Feel free to implement it, as long as backwards compatibility is kept, i.E. by introducing a new key `networks` in the Openstack provider config.
