### ISSUE TITLE
Dist-Upgrade is not fully noninteractive

### ISSUE THREAD

**Issue by cbeneke** [kubermatic/machine-controller#281]
In the latest release the `upgrade system on first boot` option results in non-functional nodes (nodes not coming up), when system files are changed. In the startup script the dist-upgrade is not called with dpkg-noninteractive mode. To fix this the line

https://github.com/kubermatic/machine-controller/blob/2e0d2f0875316755ac1a8dbc3b61d2110abf5968/pkg/userdata/ubuntu/userdata.go#L195

should be changed to

```
DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade -y
```

This might also be necessary for https://github.com/kubermatic/machine-controller/blob/2e0d2f0875316755ac1a8dbc3b61d2110abf5968/pkg/userdata/ubuntu/userdata.go#L217

**Comment by alvaroaleman** [comment]
Correct me if I am wrong, but as I understand the apt docs (I am not a debian/ubuntu expert), this is more about forcing apt to not overwrite files if possible, right?

**Comment by cbeneke** [comment]
Yes and no. When a file was changed on the system (e.g. the cloud-init config) and the package gets updated, the dpkg call (which apt uses in the background) will still ask how it should behave (the `-y` is only relevant for the apt process). As dkpg has no user session, the user query will fail and the script will hang in a infinite loop.

In our example we have nodes, being initialized on Ubuntu 16.04.4, which will upgrade to 16.04.5 and try to replace the cloud-init and motd files, as they are changed in the image we use. (But the update should ignore file-system changes anyway, as they should be user- or pipeline-managed anyways when changed initially)
