### ISSUE TITLE
Quotation marks break the cloud config

### ISSUE THREAD

**Issue by cbeneke** [kubermatic/machine-controller#304]
# User Story
As a user I want to be able to use the full range of allowed characters in passwords without breaking my cluster

## Acceptance criteria
* Any character (especially ") may be used in the cloud config fields where reasonable

# Further information
When a customer uses a " in the password, the quotation of the password breaks (ending at the ") and e.g. the controller-manager has troubles connecting to the cluster. This might also affect any other field in the cloud config, where " (and \ for escaping reasons) is used.

**Comment by bashofmann** [comment]
This is fixed by https://github.com/kubermatic/machine-controller/pull/310 and can be closed.

**Comment by alvaroaleman** [comment]
Closing as #310 fixed it
