### ISSUE TITLE
[Feature Request] Scaleway provider support

### ISSUE THREAD

**Issue by kkimdev** [kubermatic/machine-controller#338]
Scaleway's pricing is quite similar to Hetzner but a lot more popular!

**Comment by alvaroaleman** [comment]
hey @kkimdev , great idea! Would you be interested in helping out with this?

**Comment by kkimdev** [comment]
Hi, sorry but I'm not that familiar with Go and pretty occupied by my main project :(

**Comment by kkimdev** [comment]
Btw, random thought: Terraform already supports tons of providers:
- https://www.terraform.io/docs/providers/type/major-index.html
- https://www.terraform.io/docs/providers/type/cloud-index.html
- https://github.com/terraform-providers

All of them are written in Go, and seem to implement the same Terraform plugin provider interface.  For example,

- Terraform Hetzner Provider interface impl: https://github.com/terraform-providers/terraform-provider-hcloud/blob/89253889d7d425926d300f3f87efdabce89aa56f/hcloud/provider.go
- Terraform Hetzner Provider server creation: https://github.com/terraform-providers/terraform-provider-hcloud/blob/89253889d7d425926d300f3f87efdabce89aa56f/hcloud/resource_hcloud_server.go#L128

I think it should be possible to just implement Terraform plugin glue code once and use their provider implementations. wtyt?

If it can be done, we can use Terraform & machine-controller combination to fully automate deployment (e.g., https://github.com/portworx/terraporx/blob/8705613c337304d48f60b3a9d613e21f75741417/digital_ocean/kubernetes_ubuntu16/main.tf ) and ongoing node management!

**Comment by alvaroaleman** [comment]
Hey @kkimdev ,

Thanks for the hint, however the interface one has to add for a new provider is so simple that it doesn't make much sense to use the terraform code but is much easier to just write that provider: https://github.com/kubermatic/machine-controller/blob/d0ae5bd324eda69518855572a4624692061b0457/pkg/cloudprovider/cloud/provider.go#L10-L41

You basically just need to write a `Validate`, `Get`, `Create` and `Delete`, that's it, the rest maybe No-Opts. You can check out the Hetzner provider as a sample of a very simple provider: https://github.com/kubermatic/machine-controller/blob/d0ae5bd324eda69518855572a4624692061b0457/pkg/cloudprovider/provider/hetzner/provider.go

**Comment by xmudrii** [comment]
This has been implemented recently.
/close
