### ISSUE TITLE
Release Openstack FloatingIP after machine has been deleted

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#344]
Right now the machine-controller is allocating FloatingIP's whenever needed for new machines, but those FloatingIP's are not getting released from the tenant after the machine has been deleted - just removed from the machine.
So FloatingIP's will always stay in the tenant.

**Acceptance criteria**
- [ ] FloatingIP's are getting released from the tenant the machine has been deleted. The FloatingIP should only be released in case the FloatingIP has been allocated before - not if it just has been assigned to a new machine

**Comment by mrIncompetent** [comment]
@bashofmann
This works for you as well?

**Comment by bashofmann** [comment]
Works for us

**Comment by mrIncompetent** [comment]
The proper way should be a finalizer which will be added when a new floatingIp gets allocated (Not assigned)

During deletion, check if that finalizer exists. If it exists, deallocate the floatingIP

**Comment by alvaroaleman** [comment]
Estimated to be one storypoint
