### ISSUE TITLE
Parse versions via a semver library

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#36]
We need to parse the user given versions (kubelet & container runtime) to process them correctly in the end.
Especially so we can accept `v1.9.2` and `1.9.2` as input.
Currently we require the kubelet version to have a leading `v` but we dont require it for the container runtime version

**Comment by mrIncompetent** [comment]
cc @alvaroaleman

**Comment by alvaroaleman** [comment]
Is it just about the leading `v`?  If yes, we could just use `strings.HasSuffix` and add it if its not present.

**Comment by mrIncompetent** [comment]
It is about a more solid version handling in general. But it turns out docker does use semver.
Therefore this can be closed
