### ISSUE TITLE
[vSphere] 2 clusters having a node with the same name, leads to concurrency issues

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#379]
On all providers the controller uses the machine UID as tag/label on the cloud provider instance to securely identify the correct instance.
On vSphere there's no such mechanism, thus having 2 clusters with each 1 node called `node-1` will lead to issues in the controller.

**Comment by alvaroaleman** [comment]
This requires a migration to take over nodes without pre-existing UID tag.

**Comment by kdomanski** [comment]
Missing specification  of the solution to the issue.
