### ISSUE TITLE
Move all existing machine-controller CI jobs to prow

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#400]
Currently the machine-controllers CI jobs mostly run in circleci. This has the drawback that its not properly integrated into drawback and with regards to the end to end test does not allow us to test external PRs for security reasons.

*Acceptance criteria:*

* All machine-controller CI jobs are executed by Prow

**Comment by nikhita** [comment]
Closing as this is now done, yay!
