### ISSUE TITLE
Remove 'subnet' in openstack create 

### ISSUE THREAD

**Issue by jichenjc** [kubermatic/machine-controller#404]
Don't know the purpose of 

type RawConfig struct
        Subnet           providerconfig.ConfigVarString   `json:"subnet"`

looks to me openstack doesn't support this ? we can specify network (already did) but why use subnet?
https://developer.openstack.org/api-ref/compute/?expanded=create-server-detail
seems doesn't support subnet as well...

just want to check whether some history here or I can remove them in a new PR

then we can fix https://github.com/kubermatic/machine-controller/issues/263 after the PR merged (it will be come much easier)

**Comment by alvaroaleman** [comment]
Interesting point. Do you know what happens if a network has multiple subnets?

**Comment by jichenjc** [comment]
here's the configuration 

I have one net with 3 subnets (1 ipv6 and 2ipv4)

 fd0e2078-044d-4c5c-b114-3858631e6328 | private   | a8184e4f-5165-4ea8-8ed8-b776d619af6e fd9b:c245:1aaa::/64 |
|                                      |           | b3ee7cad-c672-4172-a183-8e9f069bea31 10.0.0.0/26         |
|                                      |           | 9439abfd-afa2-4264-8422-977d725a7166 10.0.2.0/24      


            # Only required if there is more than one network available
            network: "fd0e2078-044d-4c5c-b114-3858631e6328"
            # Only required if the network has more than one subnet
            #subnet: "b3ee7cad-c672-4172-a183-8e9f069bea31"
            subnet: ""


 3756ff71-f498-45f0-984e-1b9b7428358e | openstack-machinedeployment-5b6b4bcc89-md26p | ACTIVE | -          | Running     | private=10.0.2.5, fd9b:c245:1aaa:0:f816:3eff:fe06:1323 |


            network: "fd0e2078-044d-4c5c-b114-3858631e6328"
            # Only required if the network has more than one subnet
            subnet: "b3ee7cad-c672-4172-a183-8e9f069bea31"
            #subnet: ""


 2ecba5f3-0ca9-40d4-ba58-cc541cae3ed7 | openstack-machinedeployment-7b5c947fd7-zrx67 | ACTIVE | -          | Running     | private=10.0.2.12, fd9b:c245:1aaa:0:f816:3eff:fefa:d880 |


       

            # Only required if there is more than one network available
            network: "fd0e2078-044d-4c5c-b114-3858631e6328"
            # Only required if the network has more than one subnet
            #subnet: "b3ee7cad-c672-4172-a183-8e9f069bea31"
            subnet: "9439abfd-afa2-4264-8422-977d725a7166"

| 99c8865e-19d7-4d21-96b1-b43231a31998 | openstack-machinedeployment-7dd59588f4-fzg8r | ACTIVE | -          | Running     | private=10.0.2.6, fd9b:c245:1aaa:0:f816:3eff:fe82:d573 |

**Comment by jichenjc** [comment]
so from test , the latest subnet created will be selected, I am asking in openstack community and wait for more guide ...

http://lists.openstack.org/pipermail/openstack-dev/2018-November/136445.html

**Comment by alvaroaleman** [comment]
Yeah. Will you are right in that the subnet can not be passed in on the `Create` call, but rather than removing the option entirely I'd prefer to fix it

**Comment by jichenjc** [comment]
gophercloud has following ,so I think we need remove subnet then create a Network array definition...
then we can make port and FixedIP below as optional... 

// Network is used within CreateOpts to control a new server's network
// attachments.
type Network struct {
        // UUID of a network to attach to the newly provisioned server.
        // Required unless Port is provided.
        UUID string

        // Port of a neutron network to attach to the newly provisioned server.
        // Required unless UUID is provided.
        Port string

        // FixedIP specifies a fixed IPv4 address to be used on this network.
        FixedIP string
}
