### ISSUE TITLE
remove/disable leader election info log

### ISSUE THREAD

**Issue by toschneck** [kubermatic/machine-controller#424]
As operator of Kubermatic, I get every 2 seconds the following log line in the `machine-controller`:
```
cluster-9k6tgrg7hj | I1203 17:15:33.863797       1 leaderelection.go:199] successfully renewed lease kube-system/machine-controller
```
This info don't give any benefit for anyone. Only a error message when something breaks helps. So I would suggest to remove this log message or move it to a debug level. 

The issue is may a follow up from https://github.com/kubermatic/kubermatic/pull/2471:

**Comment by kdomanski** [comment]
Estimated to 2

**Comment by alvaroaleman** [comment]
This implies that all the logging we do has to be on a lower level than four

**Comment by kdomanski** [comment]
Related: kubermatic/kubermatic#2471
