### ISSUE TITLE
Controller does not end when it looses the leases

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#447]
When the machine-controller loses the leader lease (Potentially because the API server is down for a and the controller cannot renew the lease), it does not end itself.
Instead it hangs indefinitely.

What we could see so far:
- The readiness check starts to return that its unhealthy
- The liveness check does return a 200

I (@mrIncompetent) believe that the readiness check fails as one of its checks uses the lister, which might got stopped.
I assume the handling of the context within the controller does not work

**Comment by kdomanski** [comment]
Fixed in 184b4f64103038f807467db8774cf73da81e678d
