### ISSUE TITLE
Validate SSH public keys in webhook

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#469]
All public keys which get supplied within the machine object must be validated within the webhook.

Validation should work by just calling with https://github.com/golang/crypto/blob/master/ssh/keys.go#L256

**Comment by themue** [comment]
☝🏻Interested.

**Comment by mrIncompetent** [comment]
Something to note here:
When we introduce this validation, we might break existing machine objects (Which have invalid ssh keys).
We need to check if we can add an Prometheus alert to cover this

**Comment by alvaroaleman** [comment]
Alternatively, we could extend the nodedeployment events endpoint to also show events for the MachineDeployment and MachineSet: https://github.com/kubermatic/kubermatic/blob/a1745b2f2c8bb90c6fde13b30e4613d6e0e2a6bc/api/pkg/handler/v1/node/node.go#L628

**Comment by mrIncompetent** [comment]
> Alternatively, we could extend the nodedeployment events endpoint to also show events for the MachineDeployment and MachineSet: https://github.com/kubermatic/kubermatic/blob/a1745b2f2c8bb90c6fde13b30e4613d6e0e2a6bc/api/pkg/handler/v1/node/node.go#L628

I would do that on top. We cannot make sure that ever user sees those events
