### ISSUE TITLE
simple e2e test tool

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/machine-controller#47]
having a simple command line tool that would verify whether a node has been created serves not only as a good warm up exercise but also as a handy test tool.

the idea is that we would have a list of predefined machine manifests that would need some customisation in terms of credentials. The credentials could be accepted as a command line arguments and passed all the way down to the manifests. After POST'ing the given manifests to the `kube-api` server the test tool would read the current cluster state in order to determine the correctness of `machine-controller`

the test tool would use the standard `client-go` library to talk to the `api` server and would read the `kubeconfig` configuration file to discover where the cluster is actually located.

assumptions:
- cluster was created manually
- `kube config` is accessible
- there is a list of predefined machine manifests

for example, running the following command: `verify -input path_to_manifest -parameters key=value, key2=value` would print `a machine "node-docker" has been crated` to stdout.

**Comment by mrIncompetent** [comment]
lgtm
