### ISSUE TITLE
Investigate in support of baremetal providers

### ISSUE THREAD

**Issue by themue** [kubermatic/machine-controller#496]
Different technologies are available so far:

- Canonical MAAS
- RackN
- Metal³

Prototype implementations on https://rebar.digital/ already exist at https://github.com/galthaus/machine-controller/tree/drp2 . Also for Metal³ at https://github.com/metal3-io/cluster-api-provider-baremetal

**Comment by mrIncompetent** [comment]
Timebox to 4 hours

**Comment by themue** [comment]
Currently Metal³ (https://github.com/metal3-io) is investigated. It's the one chosen as bare metal provider for the Cluster API.

**Comment by nikhita** [comment]
Current status: talk to Sebastian about which provider to work on.
