### ISSUE TITLE
Use flatfile logging for docker on all distributions

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#555]
In order to make log-forwarding as easy as possible, we should use json-file logging for Docker on all distributions. This implies that we have to setup logrotate to avoid filled disks.

*Acceptance criteria:*

* Docker logs to json-files on all distributions we support
* Docker uses the same folder to log to on all distrbutions
* Logrotate is set up on all distributions to rotate docker logs
* Logrotate uses a size-based approach to determine weather to rotate the logs

**Comment by kdomanski** [comment]
We can do it for v2.11.1

**Comment by nikhita** [comment]
This is done.
