### ISSUE TITLE
Assign providerIDs to node objects that do not have a cloudprovider

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#564]
Currently, nodes on platforms that do not have a cloudprovider do not get their `providerID` property set. This will pose a problem for the cluster-autoscaler, which [identifies nodes by their providerID (https://github.com/frobware/autoscaler/blob/b4efe3c825bdeeae6b0155d8482ad1cf0e2a10f0/cluster-autoscaler/clusterstate/clusterstate.go#L947). If there are too many unindentified nodes, it will [eventually just stop working](https://github.com/frobware/autoscaler/blob/b4efe3c825bdeeae6b0155d8482ad1cf0e2a10f0/cluster-autoscaler/clusterstate/clusterstate.go#L349).

*Acceptance criteria*:
* We set the providerID on nodes and machines that do not have a cloud-provider
* We do not set the providerID when an external cloud-provide is configured

**Comment by unixfox** [comment]
Is it possible to reopen this issue? I just encountered it while having no cloud provider manager running.

I would like to use the autoscaler without using a cloud provider manager but due to the missing providerID I'm unable to do that.

**Comment by kron4eg** [comment]
@unixfox would you like to contribute this?

/reopen
/remove-lifecycle rotten

**Comment by unixfox** [comment]
I'm not a Golang developer but I don't mind learning it. I'll try to work on it in January where I'll have a bunch of time to learn this new language and thus try to contribute for this new feature.

Meanwhile, thank you for reopening the issue.

**Comment by shaase-ctrl** [comment]
Is there still interest in contributing?

**Comment by unixfox** [comment]
> Is there still interest in contributing? @unixfox

Yes but I don't have the time for that right now, and I'm not experimented enough in Golang yet.

You can close this issue if you really want to close it. That won't stop me from contributing later.

**Comment by shaase-ctrl** [comment]
Thanks for the heads up. I will move it to our icebox.
