### ISSUE TITLE
Extend circle pipeline

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#57]
Whats missing:
Building a docker image

- On push using the commit hash as docker tag
- On tag using the git tag as docker tag & latest

**Comment by alvaroaleman** [comment]
I'd also like to see this extended to verify rbac, maybe something along the lines of

* Spawning an etcd and a kube-api server with rbac enabled container
* Deploying the RBAC rules from `examples/machine-controller.yaml`
* Starting the machine-controller with a kubeconfig with the token of the service account
* Creating a dummy machine definition
* Check the `kube-apiserver` logs for `403`s
