### ISSUE TITLE
Add support for hetzner private network

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/machine-controller#599]
Hetzner recently added support for private networking, would be good to extend machine-controller to support this.

This is how it looks like with new version of terraform hetzner provider: https://github.com/kubermatic/kubeone/pull/596/files#diff-8aec760bfdbb019e856b85fc10e43205

**Comment by kron4eg** [comment]
@xmudrii please keep in mind, hetzner didn't yet released a CCM with private networking support.

ref: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/19
ref: https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/20

**Comment by alvaroaleman** [comment]
@kron4eg Why is that of any relevance?

**Comment by xmudrii** [comment]
@kron4eg I'm aware of that but I believe that it shouldn't affect the machine-controller implementation. I'm still not sure how nodes are assigned IPs (i.e. internal and external IP), but AFAIK, machine-controller doesn't use CCM for that.

**Comment by kron4eg** [comment]
just telling :)
