### ISSUE TITLE
AWS: support for encrypted root volumes

### ISSUE THREAD

**Issue by toschneck** [kubermatic/machine-controller#612]
cross ref: https://github.com/kubermatic/customer-projects/issues/107

If customers provide so called "Goden AMIs", the machine controlled need to have the possibility to create a [encrypted boot volume](https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/) . 

## Acceptance Criteria
- Kubermatic can create Machines with encrypted boot volumes using an Golden AMI
- The usage is documented

**Comment by scheeles** [comment]
I would propose this way instead a Golden AMI image:
During the create of a VM there is the option to select if the root volume should be encrypted or not.  see https://aws.amazon.com/blogs/security/how-to-quickly-launch-encrypted-ebs-backed-ec2-instances-from-unencrypted-amis/

To support this in Kubermatic, the machine-controller https://github.com/kubermatic/machine-controller needs to be enhanced to create worker-nodes with encrypted volume.

If the encryption is selected the root volume will be encrypted. check also https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-parameters

**Comment by scheeles** [comment]
Potential Implementation
The machine controller need to set Encrypted field to true https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EbsBlockDevice.html

https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/aws/provider.go#L523
