### ISSUE TITLE
Azure: Ubuntu 18.04 LTS workers fail to join the cluster

### ISSUE THREAD

**Issue by devotee101** [kubermatic/machine-controller#617]
kubeone version - [v0.10.0-alpha.1](https://github.com/kubermatic/kubeone/releases/tag/v0.10.0-alpha.1)
Kubernetes version - 1.14.2
Cloud provider - Azure
OS Worker type - Ubuntu

The cloud-init script used by the worker nodes assumes a module dependency on [nf_conntrack_ipv4](https://github.com/kubermatic/machine-controller/blob/387b36af8937da0574bf77b7de4000a59f1da39a/pkg/userdata/helper/helper.go#L69) however this module was removed in kernel 4.19 and therefore is not present on the latest Ubuntu 18.04 LTS image which is based on the 5.0.0 kernel. This causes the cloud-init script to fail on Ubuntu when it restarts [systemd-modules-load.service](https://github.com/kubermatic/machine-controller/blob/b65a6bca02e1929da123abef2c398e47bf6de27a/pkg/userdata/ubuntu/provider.go#L225).

See https://github.com/kubernetes/kubernetes/blob/master/pkg/util/ipvs/ipvs.go for an example of a similar fix.

The version of the OS image is [hardcoded](https://github.com/kubermatic/machine-controller/blob/7ebbfffa9c1455327d971d633e62bbaaa12ba461/pkg/cloudprovider/provider/azure/provider.go#L127), so the only workaround appears to be to avoid using the Ubuntu image. The latest Centos image currently works as it is based on a 3.10 kernel however this could break should Microsoft update the image to a kernel later than 4.19

**Comment by alvaroaleman** [comment]
Hey @devotee101 , thanks very much for the report. Are you interested in fixing this in `pkg/userdata/ubuntu`?

I think this is an issue for anyone using the latest 18.04.03 release and not specific for Azure.

Also ,I don't think this will be an issue for CentOS, as RedHat is very conservative in upgrading anything, I doubt they will introduce a 5.0 Kernel for CentoOS 7.
