### ISSUE TITLE
Setup logrotate

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#645]
We currently do not set up any logration, which may lead to nodes running out of disk.

*AC:*

* Logration is set up for Ubuntu
* Logration is set up for CentOS
* Logration is set up for CoreOS

**Comment by AlexMorreale** [comment]
we are doing any node configuration like adding ssh keys, logrotate, etc with daemonsets. It's a pretty nice pattern. It's similar to what `calico` does to change IP tables on boot.

**Comment by alvaroaleman** [comment]
> we are doing any node configuration like adding ssh keys, logrotate, etc with daemonsets. It's a pretty nice pattern. It's similar to what calico does to change IP tables on boot.

Yeah, thats what we are going to do. Hence, this will not be implemented within the machine-controller. Closing this as wontfix.
