### ISSUE TITLE
user nobody in machine controller dockerfile

### ISSUE THREAD

**Issue by mooperd** [kubermatic/machine-controller#677]
https://github.com/kubermatic/machine-controller/blob/08b4c2c844a82699e3c5a7b717da89a98ef7f343/Dockerfile#L21

Is there a reason for using "USER nobody" in the dockerfile? It makes any kind of debugging extremely difficult.

**Comment by kdomanski** [comment]
It's a sensible best security practice. You can easily rebuild your own image without this line if you need root for debugging.
