### ISSUE TITLE
Ubuntu swapaccounting configuration causes continuous reboot on Alicloud

### ISSUE THREAD

**Issue by moelsayed** [kubermatic/machine-controller#682]
Ubuntu nodes on Alicloud go into continuous reboot due to #666.

The most probable cause is that Alicloud are using external kernel configuration and not using the grub config on disk. Which causes the reboot case to always trigger.

Possible fix is to exclude Alicloud form this configuration.

**Comment by moadqassem** [comment]
This PR addresses the solution 
https://github.com/kubermatic/machine-controller/pull/683/files
