### ISSUE TITLE
[AWS] Disable Public IP's creation per default

### ISSUE THREAD

**Issue by toschneck** [kubermatic/machine-controller#711]
Since https://github.com/kubermatic/machine-controller/issues/544 we could disable the assignment of public IP's at the machine deployment. To ensure that the flag will set on every machine deployment, there should be an option to specify the `assignPublicIP: false`  in the `KubeOneCluster` config as enforced default.

**Comment by kdomanski** [comment]
:tada:

**Comment by xmudrii** [comment]
@toschneck Is this still relevant?

**Comment by toschneck** [comment]
@xmudrii yes - for enterprise customer this is still something relevant. 
But I think currently not a high prio as it can be enforced by the network setup...
Anyway if the enforcement get implemented, it would be also a need to configure the enforcement in kubermatic seed settings.
