### ISSUE TITLE
Upgrade KubeVirt to the latest version

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/machine-controller#727]
Since we want to sell KubeVirt to potential customers it would be good to update the KubeVirt version to the latest stable https://github.com/kubevirt/kubevirt/releases/tag/v0.26.4

**Comment by moadqassem** [comment]
The kubevirt client-go has been updated to 0.28.0 and however the operator and the api are not upgraded due to this issue https://github.com/kubevirt/kubevirt/issues/3009 . once this issue is solved we can upgrade kubevirt to the same version as the client.

**Comment by mfranczy** [comment]
@moadqassem the fix PR has been merged, could you upgrade kubevirt when you have some free time? Thanks.
