### ISSUE TITLE
Evaluate CRI-O as containter runtime for RHEL8

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/machine-controller#774]
Machine-controller recently introduced [support for RHEL8](https://github.com/kubermatic/machine-controller/pull/669).

We are currently installing Docker using Centos7 docker repository, but there are some limitations with this approach:

- Some `containerd` dependencies are excluded (i.e. `runc`) and this prevents from installing recent docker versions without hacks (by courtesy of @kron4eg 
 https://bugzilla.redhat.com/show_bug.cgi?id=1756473)
- RHEL users probably wants to have full support from RH and packages installed from centos7 docker repo are definitely out of policy.

The goal of this task is to evaluate the possibility of using CRI-O as container runtime for RHEL.

*Note that CRI-O is part of OpenShift* and probably not available through RHEL official repositories without OCP subscription (to be checked). It's not guaranteed that second point I mentioned can be addressed by this solution.

Find some pointers below:
https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/cri-o_runtime/use-crio-engine
https://github.com/openshift/openshift-ansible/blob/23eb7004a8b5dc928ea467ecc495f4fdb0ef8109/roles/openshift_node/defaults/main.yml#L13
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o

**Comment by kron4eg** [comment]
xref #393

**Comment by irozzo-1A** [comment]
CRI-O cannot be installed through RHEL repositories without openshift subscription thus is not suitable to be used as CRI for plain Kubernetes.
