### ISSUE TITLE
Add support for containerd

### ISSUE THREAD

**Issue by chrkl** [kubermatic/machine-controller#779]
Customer asked to replace Docker by another container runtime for security purposes.

- Docker uses containerd internally and adds another API layer between the kubelet and containerd that is not needed anymore
- Using fluentd / fluent-bit requires to mount /var/lib/docker/containers to the pod, which potentially grants fluetd / fluent-bit access to all running containers. Containerd logs to /var/log/containers and separates logs from other container data.

**Comment by kron4eg** [comment]
xref #393

**Comment by kron4eg** [comment]
xref https://github.com/kubermatic/kubeone/issues/1085
