### ISSUE TITLE
Do not use cluster-info configmap anymore

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#78]
Right now the `machine-controller` uses the `cluster-info` configmap to get the CACert and the endpoint for the apiserver.

Instead it should get the CACert from its `kubeconfig` or from `/run` and the apiserver endpoints from its `kubeconfig` or from the endpoints of the `kubernetes` service when running in-cluster.

This will reduce the configuration overhead and help ppl to get started faster.

**Comment by mrIncompetent** [comment]
A better solution would actually be adding a sane default/fallback.

**Cluster-Info configmap exists**
Use it

**Cluster-Info configmap does not exist**
Very explicitly log that it could not be found.
Use for the url one of the endpoints: `kubectl get endpoints kubernetes`
Get the CA from the kube-client config:
```
cfg, err := clientcmd.BuildConfigFromFlags(masterURL, kubeconfig)
if err != nil {
    glog.Fatalf("Error building kubeconfig: %v", err)
}
ca := cfg.TLSClientConfig.CAFile //will point to /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
