### ISSUE TITLE
Kube-proxy 1.8 does not work with CentOS 7

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/machine-controller#795]
`kube-proxy` 1.8 does not seem to work correctly on CentOS 7. I observed the issue with this setup:

* Cloud provider: AWS
* CentOS 7 AMI: CentOS Linux 7 x86_64 HVM EBS ENA 2002_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-0042af67f8e4dcc20.4 (ami-0e8286b71b81c3cc1)
* kube-proxy mode: IPVS

The visible effect is that services are not working or working intermittently e.g. internal DNS resolution

Lot of errors can be found in `kube-proxy` logs:

```
E0716 07:07:25.145682       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[35 198 93 90 0 0 0 0 0 0 0 0 0 0 0 0]
E0716 07:07:25.145702       1 proxier.go:1533] Failed to sync endpoint for service: 127.0.0.1:32238/TCP, err: parseIP Error ip=[35 198 93 90 0 0 0 0 0 0 0 0 0 0 0 0]
E0716 07:07:25.145770       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[35 198 93 90 0 0 0 0 0 0 0 0 0 0 0 0]
E0716 07:07:25.145789       1 proxier.go:1533] Failed to sync endpoint for service: 172.17.0.1:32238/TCP, err: parseIP Error ip=[35 198 93 90 0 0 0 0 0 0 0 0 0 0 0 0]
E0716 07:07:25.145850       1 proxier.go:1950] Failed to list IPVS destinations, error: parseIP Error ip=[35 198 93 90 0 0 0 0 0 0 0 0 0 0 0 0]
E0716 07:07:25.145868       1 proxier.go:1533] Failed to sync endpoint for service: 172.31.55.228:32238/TCP, err: parseIP Error ip=[35 198 93 90 0 0 0 0 0 0 0 0 0 0 0 0]
```

**Comment by irozzo-1A** [comment]
It seems to be related to: https://github.com/kubernetes/kubernetes/issues/89632

**Comment by kron4eg** [comment]
I suppose it's not limited to IPVS, as in kubeone we use iptables mode and it's still hangs.

**Comment by irozzo-1A** [comment]
> I suppose it's not limited to IPVS, as in kubeone we use iptables mode and it's still hangs.

indeed, iptables backend seems to be broken as well for k8s 1.17/1.18 but it's a different issue, probably we should open another ticket. The problem reported here is IPVS specific (https://github.com/kubernetes/kubernetes/blob/v1.18.2/vendor/github.com/docker/libnetwork/ipvs/netlink.go#L270).

The common denominator seems to be that recent k8s does not play well with old linux kernels (e.g. 3.10.0-1062.12.1.el7.x86_64).

**Comment by irozzo-1A** [comment]
The issue has been already fixed [here](https://github.com/kubernetes/kubernetes/pull/90678) and impacts only version from `v1.18.0` to `v.18.2` included.
