### ISSUE TITLE
Move away from Hyperkube image providing Kubelet for Flatcar machines

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/machine-controller#800]
For the same reasons as https://github.com/kubermatic/kubermatic/issues/5717, we have to get rid of hyperkube image, that is currently used to provide the Kubelet for Flatcar machines. An additional complication is that there is no official image for Kubelet at the moment.

The current strategy is to use an image maintained by some third parties e.g. [Poseidon Kubelet image](https://github.com/poseidon/kubelet#packages).

Some more context can be found here:
https://forum.kubermatic.com/t/migrate-away-from-hyperkube-in-machine-controller/70

**Comment by kron4eg** [comment]
xref https://github.com/kubermatic/kubeone/issues/984

**Comment by kron4eg** [comment]
I'm going to try this poseidon image, since it's also required for kubeone.
