### ISSUE TITLE
Support for CentOS 8

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/machine-controller#833]
The goal of this task is to provide support for CentOS 8. Currently, only CentOS 7 is officially supported.

- [ ] Verify that the right yum docker repository is used (when possible). Currently we are targeting CentOS 7.
- [ ] Add e2e tests for CentOS 8.
- [ ] Verify that nothing else in the cloud-init config should be changed.
- [ ] Update supported OS matrix.

**Comment by irozzo-1A** [comment]
Seems like it's worthy to invest in CentOS 8: https://blog.centos.org/2020/12/future-is-centos-stream/

**Comment by xrstf** [comment]
#rip
