### ISSUE TITLE
Improve e2e tests

### ISSUE THREAD

**Issue by irozzo-1A** [kubermatic/machine-controller#838]
Currently, our e2e tests are just checking that nodes are joining the cluster. This is a quite weak guarantee that things work properly. The goal of this PR is to improve the tests to add some conformance checks.

This could be considered: https://github.com/vmware-tanzu/sonobuoy/issues

Note that running full conformance tests at each PR is overkill, we should probably run a short version and have periodic jobs that run the full suite.

xref: https://github.com/kubermatic/machine-controller/issues/730

**Comment by kron4eg** [comment]
Those tasks as done at kubermatic and kubeone side.

**Comment by irozzo-1A** [comment]
As we discussed internally having mc functionalities properly e2e tested here is very valuable to detect issues earlier.
