### ISSUE TITLE
`make machine-controller` sets wrong permissions

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#84]
Doing a `make machine-controller` results in a Binary owned by root.

Can we pass in the UID from the user and do a `chown` in the build-container?

**Comment by alvaroaleman** [comment]
Yes we can, this does however not matter much because as long as you own the folder the binary is placed in, you can still move/delete the binary. The only thing you can not do is alter the binary (e.G. `echo test >> machine-controller`) or its permissions.

**Comment by mrIncompetent** [comment]
Alright, that's fine for me
