### ISSUE TITLE
rename coreos to containerLinux

### ISSUE THREAD

**Issue by mrIncompetent** [kubermatic/machine-controller#86]
We use `operatingSystem:coreos`.
As it got renamed to `ContainerLinux` we should adapt

**Comment by kdomanski** [comment]
Doesn't Digital Ocean image thingie still identify it as `coreos`?
The system itself definitely contains `ID=coreos` in its `/etc/os-release`.

**Comment by mrIncompetent** [comment]
Yes, this issue is just about the renaming the the constant used for specifying the Operating system via the machine manifest. For backwards compatibility we should though accept both.

**Comment by alvaroaleman** [comment]
I think this is a won't fix now, as [it is now named coreos again] (https://www.redhat.com/de/about/press-releases/red-hat-unveils-roadmap-coreos-integration-red-hat-openshift)
