### ISSUE TITLE
support self signed certificates for cloud provider endpoint communication

### ISSUE THREAD

**Issue by toschneck** [kubermatic/machine-controller#876]
As a customer, 
I want to be able to configure for all potential self-hosted cloud provider endpoints a self signed CA. The machine controller needs an options to support a secure communication. The provided flag `allow_insecure` is not an option for production.

Currently it's highly required for:
- Openstack, see #849 
- vsphere

**Comment by kron4eg** [comment]
Fixed by https://github.com/kubermatic/machine-controller/pull/895
