### ISSUE TITLE
Get rid of unlicensed github.com/ajeddeloh/go-json

### ISSUE THREAD

**Issue by xrstf** [kubermatic/machine-controller#913]
The repo in question has no license attached. We should not be using it.

**Comment by xrstf** [comment]
And now you know why I simply didn't bump dependencies, but instead opened an issue ;-)

**Comment by xrstf** [comment]
Unfortunately even the kinvolk fork @ https://github.com/kinvolk/container-linux-config-transpiler/ in the end uses the evil package. And the evil package is in coreos/ignition in all 0.x versions. Only v2.0+ fixes that, but that of course changes the import path and so we cannot even simply to a quick replace directive in our go.mod.

**Comment by kron4eg** [comment]
For now we have an exception added in kubermatic.
