### ISSUE TITLE
Make SSH user configurable for Azure

### ISSUE THREAD

**Issue by chrkl** [kubermatic/machine-controller#925]
The machine-controller usually injects SSH keys `ssh_authorized_keys` property of the cloud-init user-data without a specific user. This results in the use of the `default_user`, which can be configured in the `cloud-config` file of the VM image if a specific username is wanted.

On Azure an additional `OSProfile` is created that adds the SSH key to the user named by the OS (https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/azure/provider.go#L560).

If cloud-init cannot be used on Azure, the default user name should be configurable by a different way.

**Comment by kron4eg** [comment]
> The machine-controller usually injects SSH keys `ssh_authorized_keys` property of the cloud-init user-data without a specific user.

@chrkl what do you mean "without specific user". Here's how users are configured for each OS on Azure.

https://github.com/kubermatic/machine-controller/blob/564631caa1183d4c25825046f842d7dc62f60b00/pkg/cloudprovider/provider/azure/provider.go#L991-L998

I propose to close this issue as it has nothing to do.

**Comment by chrkl** [comment]
For other clouds, the SSH key is injected to the cloud-init default user, which can be configured in the used image. On Azure, the mentioned logic is used to determine the user, there's no option to deviate from this.

**Comment by kron4eg** [comment]
> which can be configured in the used image

First time hear this. ubuntu on AWS will always get ubuntu user, there is nothing to configure. Some OSes even get ec2-user, for example RHEL.

**Comment by kron4eg** [comment]
> > which can be configured in the used image
> 
> First time hear this. ubuntu on AWS will always get ubuntu user, there is nothing to configure. Some OSes even get ec2-user, for example RHEL.

And you can't configure this.

**Comment by chrkl** [comment]
These users are specified in the cloud-config section of the image (/etc/cloud/cloud.cfg). See https://cloudinit.readthedocs.io/en/latest/topics/examples.html#yaml-examples. Overriding this in a custom image works fine on other clouds.

**Comment by kron4eg** [comment]
I don't get it. What prevent you from configuring `/etc/cloud/cloud.cfg` to use whatever corresponding user to the given OS?

**Comment by chrkl** [comment]
This is not effective on Azure due to the applied OsProfile in https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/azure/provider.go#L560

**Comment by kron4eg** [comment]
Calculated (after the OS) user
https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/azure/provider.go#L539

is used in OsProfile
https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/azure/provider.go#L558

How is this "not effective"?

**Comment by chrkl** [comment]
I mean the default user settings from the image are overwritten by the OsProfile.
