### ISSUE TITLE
Mounted cloud-init ISO images cause warnings when updating ESXi hosts 

### ISSUE THREAD

**Issue by chrkl** [kubermatic/machine-controller#951]
The attached cloud-init ISO images cause warning during a ESXi host update:

![image](https://user-images.githubusercontent.com/318416/116070237-a7749600-a68c-11eb-83b3-0b50d49acb48.png)
![image (1)](https://user-images.githubusercontent.com/318416/116070247-a9d6f000-a68c-11eb-8f1a-b6499ab2e4db.png)

**Comment by toschneck** [comment]
we have the same problems at other customers as well
