### ISSUE TITLE
Flatcar containerd support

### ISSUE THREAD

**Issue by kron4eg** [kubermatic/machine-controller#952]
Turns out [Flatcar got the CRI plugin enabled][ref] in containerd, but they have non standard path to containerd-shim-runc binaries so we need to adjust generated containerd to that.

[ref]: https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/

**Comment by toschneck** [comment]
cc @mfahlandt FYI

**Comment by HaveFun83** [comment]
@kron4eg @mlavacca sorry to comment on a closed ticket but how can i enable containerd within a machine-deployment?

**Comment by kron4eg** [comment]
@HaveFun83 you have to have machine-controller running with -container-runtime=containerd and then, see https://docs.kubermatic.com/kubeone/master/cheat_sheets/rollout_machinedeployment/

**Comment by HaveFun83** [comment]
> @HaveFun83 you have to have machine-controller running with -container-runtime=containerd and then, see https://docs.kubermatic.com/kubeone/master/cheat_sheets/rollout_machinedeployment/

thanks a lot i add the flag `-node-container-runtime: containerd` to the machine-controller deployemnt
