### ISSUE TITLE
Support Hetzner Firewalls 

### ISSUE THREAD

**Issue by EarthlingDavey** [kubermatic/machine-controller#982]
Using terraform + kubeone. If using Kubermatic machine-controller to manage worker nodes there is currently no way to assign a firewall to the worker nodes.

Desired outcome.

- If a firewall id is found in the `kubeone_workers` object...
- Run `kubeone apply --manifest kubeone.yaml --tfjson output.json` to create the worker nodes with the firewall assignment.
- Scaling with `kubectl scale -n kube-system machinedeployment development-pool1 --replicas=x` to manage firewall assignment.

I'm on kubernetes slack #kubeone incase the issue in not clear there is a discussion there. Also, with another user who has the same issue.

**Comment by kron4eg** [comment]
Hello, 
TBH we ourselves don't need such features and there is no plan to work on it, but we'd happily accept a contribution.

**Comment by EarthlingDavey** [comment]
Hi, thanks for the quick response - I appreciate it.

As a newbie to  kubeone, machine-controller etc. Do you mind me asking, is this actually the best (or a good) solution to my issue?

I think so, but I'm not confident. For example, I could request hetzner to target firewalls by worker node label.

PS. the link for joining kubermatic slack down http://slack.kubermatic.io/

**Comment by kron4eg** [comment]
One solution could be: introduction of firewall_id to https://github.com/kubermatic/machine-controller/blob/b51933b55d3474a6f26014e56bee985a78aa0f13/pkg/cloudprovider/provider/hetzner/provider.go#L57-L65
and handle it in this method
https://github.com/kubermatic/machine-controller/blob/b51933b55d3474a6f26014e56bee985a78aa0f13/pkg/cloudprovider/provider/hetzner/provider.go#L193

On the other hand, Calico can handle firewall protection of hosts, please see: https://docs.projectcalico.org/about/about-network-policy#ability-to-protect-hosts-and-vms

**Comment by EarthlingDavey** [comment]
Thanks for the suggestion. I'll try this

And, avoid Calico so as not to add complexity to my project.

**Comment by EarthlingDavey** [comment]
Hi - I've made [this commit](https://github.com/usedandloved/machine-controller/commit/563b8a270866ac47a0169e33059724b6251f791a) based on copying the edits for [Add support for Hetzner Private Networks #627](https://github.com/kubermatic/machine-controller/pull/627/files).

It's untested, I haven't run go yet. I would like to get e2e tests up and running, but following the docs, I am getting an error `failed to create machine at cloudprovider, due to network "machine-controller-e2e" does not exist`.

It would be awesome if either someone can assist in getting the e2e running (and passing 😅).
